import { FloatingInput, FloatingSelect, FloatingTextarea } from "@/Components/Form";import { router, useForm, usePage } from '@inertiajs/react';
import { useEffect, useState } from 'react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import ConfirmDialog from '@/Components/ConfirmDialog';
import CrudDetailsModal from '@/Components/Crud/CrudDetailsModal';
import CrudFormModal from '@/Components/Crud/CrudFormModal';
import CrudSection from '@/Components/Crud/CrudSection';
import CrudSummaryGrid from '@/Components/Crud/CrudSummaryGrid';
import CrudTable from '@/Components/Crud/CrudTable';
import FilePreviewPanel from '@/Components/Crud/FilePreviewPanel';
import FileAttachmentPanel from '@/Components/Crud/FileAttachmentPanel';
import PageHeader from '@/Components/PageHeader';
import { formatReportDate } from '@/Utils/dateFormatters';
import WorkflowTabs from './WorkflowTabs';

const empty = { protected_area_id: '', target_office: '', activity_name: '', document_type: '', quarter: 'Quarter 1', date_conducted: '', date_accomplished: '', date_report_released_cenro: '', date_received_penro: '', date_endorsed_regional: '', mov: null, delete_mov: false, remarks: '' };
const label = 'block text-xs font-semibold text-gray-700 dark:text-gray-300';
const display = (value) => value === null || value === undefined || value === '' ? '—' : value;
const badgeClass = (value) => ({ Outstanding: 'bg-emerald-500 text-white', 'Very Satisfactory': 'bg-green-600 text-white', Satisfactory: 'bg-amber-400 text-amber-950', Unsatisfactory: 'bg-orange-500 text-white', Poor: 'bg-red-600 text-white', 'Report Submitted': 'bg-green-600 text-white', 'Report Not Yet Submitted': 'bg-red-600 text-white', 'Ongoing Preparation at CENRO Level': 'bg-blue-600 text-white', 'Pending Submission by CENRO': 'bg-blue-600 text-white' })[value] || 'bg-gray-500 text-white';
const Badge = ({ value }) => <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${badgeClass(value)}`}>{display(value)}</span>;
const Detail = ({ label, children }) => <div><span className="block text-xs text-gray-500">{label}</span><span className="font-semibold text-gray-800 dark:text-gray-200">{children}</span></div>;

export default function MaintenanceReports({ reports = {}, protectedAreas = [], filters = {} }) {
  const { auth = {} } = usePage().props;
  const canCreate = Boolean(auth.canCreateImea),canUpdate = Boolean(auth.canUpdateImea),canDelete = Boolean(auth.canDeleteImea);
  const rows = reports.data || [],links = reports.links || [];
  const [selected, setSelected] = useState(null),[editing, setEditing] = useState(null),[deleting, setDeleting] = useState(null),[search, setSearch] = useState(filters.search || ''),[preview, setPreview] = useState(null);
  const form = useForm(empty);
  const existingMov = editing?.mov || null;
  useEffect(() => () => {if (preview?.temporary) URL.revokeObjectURL(preview.url);}, [preview]);
  useEffect(() => {if (!selected) return;const refreshed = rows.find((row) => row.id === selected.id);if (refreshed) setSelected(refreshed);}, [reports.data]);
  const openForm = (report) => {setEditing(report || {});form.clearErrors();form.setData(report ? { ...empty, ...report, mov: null, delete_mov: false } : empty);setPreview(report?.mov || null);};
  const closeForm = () => {setEditing(null);setPreview(null);form.reset();form.clearErrors();};
  const selectMov = (file) => {form.setData((data) => ({ ...data, mov: file, delete_mov: false }));setPreview(file ? { name: file.name, type: file.type, size: file.size, url: URL.createObjectURL(file), temporary: true } : existingMov);};
  const submit = (event) => {event.preventDefault();const isEdit = Boolean(editing?.id);form.transform((data) => isEdit ? { ...data, _method: 'put' } : data);form.post(isEdit ? route('imea.maintenance-reports.update', editing.id) : route('imea.maintenance-reports.store'), { forceFormData: true, preserveScroll: true, onSuccess: closeForm });};
  const visit = (changes) => router.get(route('imea.maintenance-reports.index'), { ...filters, search, ...changes }, { preserveState: true, preserveScroll: true, replace: true });
  const columns = [
  { key: 'protected_area_name', label: 'Name of PA', tooltip: (row) => row.protected_area_name, render: (row) => <span className="font-semibold text-gray-900 dark:text-white">{display(row.protected_area_name)}</span> },
  { key: 'activity_name', label: 'Name of Activity', tooltip: (row) => row.activity_name, render: (row) => display(row.activity_name) },
  { key: 'date_conducted', label: 'Date Conducted', render: (row) => <span className="block min-w-32 whitespace-normal">{display(row.date_conducted)}</span> },
  { key: 'document_type', label: 'Type of Document', render: (row) => display(row.document_type) },
  { key: 'quarter', label: 'Quarter', render: (row) => display(row.quarter) },
  { key: 'date_accomplished', label: 'Date Accomplished', render: (row) => formatReportDate(row.date_accomplished) },
  { key: 'timeliness', label: 'Timeliness', render: (row) => <Badge value={row.timeliness} /> },
  { key: 'submission_status', label: 'Status of Submission', render: (row) => <Badge value={row.submission_status} /> }];

  const filtersUi = <form onSubmit={(event) => {event.preventDefault();visit({ page: 1 });}} className="grid gap-3 md:grid-cols-5"><div className={label}><FloatingInput id="maintenancereports-search" label="Search" type="search" value={search} onChange={(event) => setSearch(event.target.value)} size="sm" /></div><div className={label}><FloatingSelect id="maintenancereports-protected-area" label="Protected Area" value={filters.protected_area_id || ''} onChange={(event) => visit({ protected_area_id: event.target.value, page: 1 })}><option value="">All</option>{protectedAreas.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</FloatingSelect></div><div className={label}><FloatingSelect id="maintenancereports-quarter" label="Quarter" value={filters.quarter || ''} onChange={(event) => visit({ quarter: event.target.value, page: 1 })}><option value="">All</option>{[1, 2, 3, 4].map((number) => <option key={number}>Quarter {number}</option>)}</FloatingSelect></div><div className="flex items-end gap-2 md:col-span-2"><button className="rounded-xl bg-green-700 px-4 py-2.5 text-xs font-bold text-white hover:bg-green-800">Search</button><button type="button" onClick={() => {setSearch('');router.get(route('imea.maintenance-reports.index'));}} className="rounded-xl border border-gray-300 px-4 py-2.5 text-xs font-bold dark:border-gray-700 dark:text-white">Reset</button></div></form>;
  const pagination = links.length > 3 ? <div className="flex flex-wrap gap-1">{links.map((link, index) => <button key={index} disabled={!link.url || link.active} onClick={() => link.url && router.get(link.url)} className={`rounded-lg px-3 py-1.5 text-xs font-bold ${link.active ? 'bg-green-700 text-white' : 'bg-gray-100 dark:bg-gray-700 dark:text-white'} disabled:opacity-50`} dangerouslySetInnerHTML={{ __html: link.label }} />)}</div> : null;

  return <AuthenticatedLayout title="Maintenance of Ecotourism Facilities Report"><PageHeader title="Maintenance of Ecotourism Facilities Report" description="Ecotourism Development Program — quarterly submission using the 7-working-day standard." actions={canCreate && <button onClick={() => openForm(null)} className="rounded-xl bg-green-700 px-4 py-2.5 text-xs font-bold text-white shadow-md hover:bg-green-800">+ Add Report</button>} /><WorkflowTabs active="maintenance" /><div className="mt-5"><CrudTable title="Maintenance of PAMO and/or Ecotourism Facilities" subtitle={`${reports.total ?? rows.length} quarterly reports`} helperText="Click any row to view full details" columns={columns} rows={rows} rowKey="id" onRowClick={setSelected} filters={filtersUi} pagination={pagination} emptyTitle="No maintenance reports found" emptyDescription="No quarterly maintenance reports match the selected filters." tableClassName="min-w-[1150px]" /></div>
        <CrudDetailsModal open={Boolean(selected)} icon="📋" title="Maintenance Report Details" subtitle={selected?.protected_area_name || ''} onClose={() => setSelected(null)} canEdit={canUpdate} canDelete={canDelete} onEdit={() => {openForm(selected);setSelected(null);}} onDelete={() => setDeleting(selected)} editLabel="Edit Report" deleteLabel="Delete Report" summary={selected && <CrudSummaryGrid items={[{ label: 'Quarter', value: selected.quarter }, { label: 'Type of Document', value: selected.document_type }, { label: 'Timeliness', render: () => <Badge value={selected.timeliness} /> }, { label: 'Submission Status', render: () => <Badge value={selected.submission_status} /> }]} />} attachments={selected?.mov && <FilePreviewPanel file={selected.mov} title="MOV / Supporting Document" heightClass="h-[420px]" />}><ReportDetails report={selected} /></CrudDetailsModal>
        <CrudFormModal open={editing !== null} mode={editing?.id ? 'edit' : 'create'} icon="📋" title={editing?.id ? 'Edit Maintenance Report' : 'Add Maintenance Report'} subtitle={editing?.id ? 'Update report details and review the MOV side-by-side.' : 'Record quarterly maintenance compliance details and supporting MOV.'} onClose={closeForm} onSubmit={submit} processing={form.processing} errors={form.errors} saveLabel={editing?.id ? 'Update Report' : 'Save Report'} preview={<FilePreviewPanel file={preview} title="Live Document Preview" />}><ReportForm form={form} protectedAreas={protectedAreas} selectMov={selectMov} existingMov={existingMov} preview={preview} setPreview={setPreview} canManage={editing?.id ? canUpdate : canCreate} /></CrudFormModal>
        <ConfirmDialog open={Boolean(deleting)} title="Delete Maintenance Report?" message={`Delete “${deleting?.activity_name || 'this report'}”?`} confirmLabel="Delete Report" variant="danger" onCancel={() => setDeleting(null)} onConfirm={() => router.delete(route('imea.maintenance-reports.destroy', deleting.id), { preserveScroll: true, onSuccess: () => {setDeleting(null);setSelected(null);} })} />
    </AuthenticatedLayout>;
}

function ReportForm({ form, protectedAreas, selectMov, existingMov, preview, setPreview, canManage }) {
  const change = (name) => (event) => form.setData(name, event.target.value);
  const error = (name) => form.errors[name] && <span className="mt-1 block text-xs text-red-500">{form.errors[name]}</span>;
  const calculated = editingCalculations(form.data);
  return <><CrudSection title="General / Report Information"><div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <div className={label}><FloatingInput id="maintenancereports-target-office" label="Target Office" value={form.data.target_office} onChange={change('target_office')} />{error('target_office')}</div>
        <div className={label}><FloatingSelect id="maintenancereports-protected-area" label="Protected Area" value={form.data.protected_area_id} onChange={change('protected_area_id')}><option value="">Select Protected Area</option>{protectedAreas.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</FloatingSelect>{error('protected_area_id')}</div>
        <div className={label}><FloatingInput id="maintenancereports-name-of-activity" label="Name of Activity" value={form.data.activity_name} onChange={change('activity_name')} />{error('activity_name')}</div>
        <div className={label}><FloatingSelect id="maintenancereports-type-of-document" label="Type of Document" value={form.data.document_type} onChange={change('document_type')} disabled={form.processing}><option value="">Select Type of Document</option><option value="Final Report">Final Report</option><option value="Progress Report">Progress Report</option></FloatingSelect>{error('document_type')}</div>
        <div className={label}><FloatingSelect id="maintenancereports-quarter" label="Quarter" value={form.data.quarter} onChange={change('quarter')}><option value="">Select Quarter</option>{[1, 2, 3, 4].map((number) => <option key={number}>Quarter {number}</option>)}</FloatingSelect>{error('quarter')}</div>
        <div className={label}><FloatingInput id="maintenancereports-date-conducted" label="Date Conducted" value={form.data.date_conducted} onChange={change('date_conducted')} placeholder="Enter date or coverage period" />{error('date_conducted')}</div>
    </div></CrudSection><CrudSection title="Submission Information"><div className="grid grid-cols-1 gap-4 sm:grid-cols-2">{[['date_accomplished', 'Date Accomplished'], ['date_report_released_cenro', 'Date Report Released by CENRO Records'], ['date_received_penro', 'Date Received by PENRO Records'], ['date_endorsed_regional', 'Date Endorsed to Regional Office']].map(([name, text]) => <div key={name} className={label}><FloatingInput id={`imea-maintenance-${name}`} label={text} type="date" value={form.data[name] || ''} onChange={change(name)} />{error(name)}</div>)}</div>{calculated.length > 0 && <div className="mt-5 grid grid-cols-1 gap-3 sm:grid-cols-2">{calculated.map(([text, value]) => <div key={text} className="rounded-xl border border-gray-200 bg-gray-50 p-3 dark:border-gray-700 dark:bg-gray-900"><p className="mb-2 text-[11px] font-bold uppercase tracking-wide text-gray-500">{text}</p><Badge value={value} /></div>)}</div>}</CrudSection>
    <CrudSection title="Attachment / MOV & Remarks"><div className="space-y-5"><FileAttachmentPanel id="imea-maintenance-mov" label="MOV Attachment" required={!existingMov} accept=".pdf,.jpg,.jpeg,.png,.doc,.docx" acceptedTypesHint="PDF, JPG, PNG, DOC, or DOCX" maxSizeHint="Maximum 10 MB" existingFiles={existingMov && !form.data.delete_mov ? [existingMov] : []} selectedFiles={form.data.mov ? [form.data.mov] : []} activeFile={preview} onSelectFile={setPreview} onChange={selectMov} onRemoveExisting={() => {form.setData('delete_mov', true);setPreview(null);}} error={form.errors.mov} disabled={form.processing} canManage={canManage} /><div className={label}><FloatingTextarea id="maintenancereports-remarks" label="Remarks" rows="4" value={form.data.remarks} onChange={change('remarks')} />{error('remarks')}</div></div></CrudSection></>;
}
function editingCalculations(data) {return [['Deadline for Submission to PENRO', data.deadline_submission], ['Number of Days Complied', data.number_days_complied], ['Timeliness', data.timeliness], ['Status of Submission', data.submission_status]].filter(([, value]) => value !== null && value !== undefined && value !== '');}
function ReportDetails({ report }) {if (!report) return null;return <div className="space-y-5"><CrudSection title="General Information"><div className="grid gap-4 sm:grid-cols-2"><Detail label="Target Office">{display(report.target_office)}</Detail><Detail label="Protected Area">{display(report.protected_area_name)}</Detail><Detail label="Activity">{display(report.activity_name)}</Detail><Detail label="Type of Document">{display(report.document_type)}</Detail><Detail label="Quarter">{display(report.quarter)}</Detail><Detail label="Date Conducted">{display(report.date_conducted)}</Detail></div></CrudSection><CrudSection title="Submission Information"><div className="grid gap-4 sm:grid-cols-2"><Detail label="Date Accomplished">{formatReportDate(report.date_accomplished)}</Detail><Detail label="Deadline for Submission to PENRO">{formatReportDate(report.deadline_submission)}</Detail><Detail label="Date Report Released by CENRO Records">{formatReportDate(report.date_report_released_cenro)}</Detail><Detail label="Date Received by PENRO Records">{formatReportDate(report.date_received_penro)}</Detail><Detail label="Number of Days Complied">{display(report.number_days_complied)}</Detail><Detail label="Timeliness at PENRO Level"><Badge value={report.timeliness} /></Detail><Detail label="Status of Submission"><Badge value={report.submission_status} /></Detail><Detail label="Date Endorsed to Regional Office">{formatReportDate(report.date_endorsed_regional)}</Detail><Detail label="PENRO Delay">{display(report.total_days_delayed_penro)}</Detail></div></CrudSection><CrudSection title="Remarks"><p>{report.remarks || 'None.'}</p></CrudSection></div>;}
