import React, { memo, useEffect, useMemo, useRef, useState } from 'react';
const readable = (n) => { if (!Number.isFinite(n)) return '0 B'; if (n < 1024) return `${n} B`; const u=['KB','MB','GB']; let i=-1,s=n; do { s/=1024; i++; } while(s>=1024&&i<u.length-1); return `${s.toFixed(s>=10?1:2)} ${u[i]}`; };
const ext = (name='') => name.split('.').pop()?.toLowerCase() || '';
const typeBadge = (file) => ['jpg','jpeg','png','gif','webp'].includes(ext(file?.name)) ? 'IMG' : ext(file?.name)==='pdf' ? 'PDF' : ['doc','docx'].includes(ext(file?.name)) ? 'DOC' : ['xls','xlsx'].includes(ext(file?.name)) ? 'XLS' : (ext(file?.name).slice(0,4).toUpperCase() || 'FILE');
const same = (a,b) => a?.name===b?.name && (a?.size==null || b?.size==null || a?.size===b?.size) && (a?.lastModified==null || b?.lastModified==null || a?.lastModified===b?.lastModified);
const active = (a,b) => same(a,b) || (a?.url && b?.url && a.url===b.url) || (a?.id && b?.id && a.id===b.id);
function AttachmentDropzone({ id='attachment', label='Report Attachment', files, selectedFiles, onFilesChange, onChange, accept='', allowedExtensions=[], maxSizeBytes, maxSize, maxFiles, multiple=false, disabled=false, required=false, existingAttachments=[], existingFiles=[], activeFile, onSelectFile, onRemoveExisting, error, validationErrors, helperText, acceptedTypesHint, maxSizeHint, requiredMessage='Please select an attachment.', canManage=true }) {
 const input=useRef(null), [dragging,setDragging]=useState(false), [clientError,setClientError]=useState(null);
 const selected=useMemo(()=>{const value=files ?? selectedFiles; return multiple ? (Array.isArray(value)?value:value?[value]:[]) : (Array.isArray(value)?value.filter(Boolean):value?[value]:[]);},[files,selectedFiles,multiple]);
 const existing=Array.isArray(existingAttachments)&&existingAttachments.length?existingAttachments:(Array.isArray(existingFiles)?existingFiles:existingFiles?[existingFiles]:[]);
 useEffect(()=>{if(selected.length===0&&existing.length===0)setClientError(null);},[selected.length,existing.length]);
 const limit=Number(maxSizeBytes??maxSize??0)||0; const accepted=useMemo(()=>[...String(accept).split(',').map(v=>v.trim().toLowerCase()).filter(Boolean),...allowedExtensions.map(v=>String(v).replace(/^\./,'').toLowerCase())],[accept,allowedExtensions]);
 const emit=(next)=>{onFilesChange?.(next);onChange?.(multiple?next:(next[0]||null));};
 const add=(list)=>{const incoming=Array.from(list||[]);if(incoming.length===1)setClientError(null);const valid=[];for(const file of incoming){const e=ext(file.name);const ok=!accepted.length||accepted.some(r=>r.startsWith('.')?r===`.${e}`:r.includes('/')?(file.type===r||(r.endsWith('/*')&&file.type.startsWith(r.slice(0,-1)))):r===e);if(!ok){setClientError(`${file.name} is not an allowed file type.`);continue;}if(limit&&file.size>limit){setClientError(`${file.name} exceeds the maximum file size.`);continue;}if(!selected.some(x=>same(x,file))&&!valid.some(x=>same(x,file)))valid.push(file);}const cap=Number(maxFiles??(multiple?0:1));const overflow=cap>0&&(multiple?selected.length+valid.length>cap:incoming.length>1);const next=multiple?[...selected,...valid].slice(0,cap>0?cap:undefined):(selected.length&&incoming.length>1?selected:(valid.length?valid.slice(0,1):selected));if(overflow)setClientError(cap===1?"Only one attachment is allowed for this module.":`You can select up to ${cap} files.`);else if(valid.length)setClientError(null);emit(next);};
 const total=selected.reduce((s,f)=>s+(f.size||0),0);
 return <section className="space-y-2 border-t border-gray-100 pt-2"><div className="text-sm font-semibold text-slate-700">{label}{required?' *':''}</div><button type="button" id={id} disabled={disabled||!canManage} onClick={()=>input.current?.click()} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input.current?.click();}}} onDragOver={e=>{e.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);add(e.dataTransfer.files);}} className={`flex h-[100px] w-full flex-col items-center justify-center rounded-lg border-2 border-dashed px-3 text-center focus:outline-none focus:ring-2 focus:ring-emerald-500 ${dragging?'border-emerald-600 bg-emerald-50':'border-emerald-300 bg-emerald-50/40'} ${disabled?'cursor-not-allowed opacity-60':'cursor-pointer hover:bg-emerald-50'}`}><span className="text-lg text-emerald-700" aria-hidden="true">↥</span><span className="text-sm font-medium text-emerald-800">Drag &amp; drop files here or click to browse</span><span className="text-xs text-slate-500">{helperText||acceptedTypesHint||'Choose an attachment'}{maxSizeHint?` · ${maxSizeHint}`:''}</span></button><input ref={input} type="file" className="hidden" accept={accept} multiple={multiple} disabled={disabled||!canManage} onChange={e=>{add(e.target.files);e.target.value='';}} />
 {existing.length>0&&<div className="space-y-1"><div className="text-xs font-semibold text-slate-600">Current files</div>{existing.map((f,i)=><div key={f.id??f.url??i} className="flex items-center gap-2 rounded-md border border-slate-200 bg-white px-2 py-1.5 text-sm"><button type="button" onClick={()=>onSelectFile?.(f)} className="min-w-0 flex-1 truncate text-left text-emerald-800 hover:underline">{f.name||`File ${i+1}`}</button>{canManage&&onRemoveExisting&&<button type="button" onClick={()=>onRemoveExisting(f)} className="px-1 text-red-600" aria-label={`Remove ${f.name||`file ${i+1}`}`}>×</button>}</div>)}</div>}
 {selected.length>0&&<div className="space-y-1">{selected.map((f,i)=><div key={`${f.name}-${f.lastModified}-${i}`} className={`flex items-center gap-2 rounded-md border px-2 py-1.5 text-sm ${active(activeFile,f)?'border-emerald-500 bg-emerald-50':'border-slate-200 bg-white'}`}><button type="button" onClick={()=>onSelectFile?.(f)} className="flex min-w-0 flex-1 items-center gap-2 text-left"><span className="rounded bg-emerald-100 px-1.5 py-0.5 text-[10px] font-bold text-emerald-800">{typeBadge(f)}</span><span className="truncate">{f.name}</span><span className="ml-auto whitespace-nowrap text-xs text-slate-500">{readable(f.size)}</span></button><button type="button" onClick={()=>{setClientError(null);emit(selected.filter((_,j)=>j!==i));}} className="px-1 text-slate-500 hover:text-red-600" aria-label={`Remove ${f.name}`}>×</button></div>)}<div className="flex items-center justify-between text-xs text-slate-500"><span>{selected.length} file{selected.length===1?'':'s'} selected · {readable(total)} total</span>{selected.length>1&&<button type="button" onClick={()=>{setClientError(null);emit([]);}} className="font-medium text-emerald-700 hover:underline">Clear All</button>}</div></div>}
 {(clientError||error||validationErrors)&&<div className="text-sm text-red-600" role="alert">{clientError||error||validationErrors}</div>}{required&&!selected.length&&!existing.length&&<span className="sr-only">{requiredMessage}</span>}</section>;
}
export default memo(AttachmentDropzone);