services:
  - type: web
    name: cds-system
    runtime: php
    buildCommand: "composer install --optimize-autoloader --no-dev"
    startCommand: "php artisan config:clear && php artisan serve --host=0.0.0.0 --port=$PORT"
    envVars:
      - key: APP_DEBUG
        value: "false"
