import { useEffect } from 'react';
import Button from '@/Components/Button';
import CrudModalHeader from './CrudModalHeader';
import CrudModalFooter from './CrudModalFooter';

export default function CrudFormModal({ open, mode = 'create', icon, title, subtitle, onClose, onSubmit, processing = false, errors = {}, children, preview, canDelete = false, onDelete, canSave = true, backLabel, saveLabel, deleteLabel = 'Delete Record', maxWidth = 'max-w-6xl' }) {
    useEffect(() => { if (!open || processing) return; const onKey = event => event.key === 'Escape' && onClose?.(); document.addEventListener('keydown', onKey); return () => document.removeEventListener('keydown', onKey); }, [open, processing, onClose]);
    if (!open) return null;
    const resolvedSaveLabel = saveLabel || (mode === 'edit' ? 'Save Changes' : 'Save Record');
    return <div className="fixed inset-0 z-50 flex items-center justify-center bg-gray-950/60 p-4 backdrop-blur-xs"><form onSubmit={onSubmit} role="dialog" aria-modal="true" aria-label={title} className={`flex max-h-[94vh] w-full flex-col overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-2xl dark:border-gray-800 dark:bg-gray-900 ${maxWidth}`}><CrudModalHeader icon={icon} title={title} subtitle={subtitle} onClose={processing ? undefined : onClose} /><div className="custom-table-scrollbar min-h-0 flex-1 overflow-y-auto p-5">{Object.keys(errors || {}).length > 0 && <div className="mb-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700 dark:border-red-900 dark:bg-red-950/40 dark:text-red-300" role="alert"><p className="font-bold">Please correct the following:</p><ul className="mt-1 list-disc pl-5">{Object.values(errors).map((error, index) => <li key={index}>{error}</li>)}</ul></div>}<div className={preview ? 'grid grid-cols-1 gap-5 lg:grid-cols-12' : ''}><div className={preview ? 'space-y-4 lg:col-span-7' : 'space-y-4'}>{children}</div>{preview && <div className="lg:col-span-5">{preview}</div>}</div></div><CrudModalFooter left={canDelete && onDelete ? <Button variant="danger" onClick={onDelete} disabled={processing}>{deleteLabel}</Button> : null}><Button variant="secondary" onClick={onClose} disabled={processing}>{backLabel || (mode === 'edit' ? 'Back' : 'Cancel')}</Button>{canSave && <Button variant="primary" type="submit" disabled={processing}>{processing ? (mode === 'edit' ? 'Updating…' : 'Saving…') : resolvedSaveLabel}</Button>}</CrudModalFooter></form></div>;
}
