export default function FileAttachmentPanel({ id, label = 'Attachment', multiple = false, accept, acceptedTypesHint, maxSizeHint, existingFiles = [], selectedFiles = [], activeFile, onSelectFile, onChange, onRemoveExisting, error, disabled = false, canManage = true }) {
    const files = Array.isArray(existingFiles) ? existingFiles : existingFiles ? [existingFiles] : [];
    const selected = Array.isArray(selectedFiles) ? selectedFiles : selectedFiles ? [selectedFiles] : [];
    const isActive = file => activeFile && (activeFile.id === file.id || activeFile.url === file.url || activeFile.name === file.name);
    return <section className="space-y-3 border-t border-gray-100 pt-2 dark:border-gray-800">
        <div><label htmlFor={id} className="block text-xs font-semibold text-gray-700 dark:text-gray-300">{label}</label>{(acceptedTypesHint || maxSizeHint) && <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">{[acceptedTypesHint, maxSizeHint].filter(Boolean).join(' · ')}</p>}</div>
        {files.length > 0 && <div><span className="mb-1 block text-xs font-semibold text-gray-600 dark:text-gray-400">Current Files (Click to Preview):</span><div className="flex flex-wrap gap-2">{files.map((file, index) => <span key={file.id ?? file.url ?? index} className={`inline-flex max-w-full items-center gap-2 rounded-full border px-3 py-1.5 text-xs font-semibold transition ${isActive(file) ? 'border-green-600 bg-green-700 text-white' : 'border-green-200 bg-green-50 text-green-800 hover:bg-green-100 dark:border-green-900 dark:bg-green-950/50 dark:text-green-300'}`}><button type="button" onClick={() => onSelectFile?.(file)} className="min-w-0 truncate text-left" title={file.name}>{file.name || `File ${index + 1}`}</button>{file.url && !onSelectFile && <a href={file.url} target="_blank" rel="noreferrer" className="font-bold hover:underline">Open</a>}{canManage && onRemoveExisting && <button type="button" onClick={() => onRemoveExisting(file)} className={isActive(file) ? 'font-bold text-white' : 'font-bold text-red-600'} aria-label={`Remove ${file.name || 'file'}`}>×</button>}</span>)}</div></div>}
        {canManage && <input id={id} type="file" multiple={multiple} accept={accept} disabled={disabled} onChange={event => onChange?.(multiple ? Array.from(event.target.files || []) : (event.target.files?.[0] || null), event)} className="block w-full cursor-pointer rounded-xl border border-gray-300 bg-white text-xs text-gray-500 file:mr-4 file:rounded-xl file:border-0 file:bg-green-50 file:px-4 file:py-2 file:text-xs file:font-semibold file:text-green-700 hover:file:bg-green-100 disabled:cursor-not-allowed disabled:opacity-60 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-300" />}
        {selected.length > 0 && <div className="flex flex-wrap gap-2">{selected.map((file, index) => <span key={file?.name ?? index} className="inline-flex max-w-full items-center gap-2 rounded-full border border-blue-200 bg-blue-50 px-3 py-1.5 text-xs font-semibold text-blue-800 dark:border-blue-900 dark:bg-blue-950/50 dark:text-blue-300"><span className="truncate">New: {file?.name || `File ${index + 1}`}</span></span>)}</div>}
        {error && <p className="text-xs font-medium text-red-600 dark:text-red-400" role="alert">{error}</p>}
    </section>;
}
