const extensionOf = file => file?.name?.split('.').pop()?.toLowerCase() || '';

export default function FilePreviewPanel({ file, title = 'Live Document Preview', emptyText = 'No file selected for preview', className = '', heightClass = 'h-[650px]' }) {
    const extension = extensionOf(file);
    const isImage = file?.type?.startsWith?.('image/') || ['jpg', 'jpeg', 'png', 'gif', 'webp'].includes(extension);
    const isPdf = file?.type === 'application/pdf' || extension === 'pdf';
    return <aside className={`overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-xl dark:border-gray-800 dark:bg-gray-900 ${className}`}>
        <div className="flex items-center justify-between gap-3 border-b border-gray-100 px-5 py-4 dark:border-gray-800"><div className="min-w-0"><h3 className="text-xs font-bold uppercase tracking-wider text-green-800 dark:text-green-400">{title}</h3>{file && <p className="mt-1 truncate text-xs font-medium text-gray-600 dark:text-gray-300" title={file.name}>{file.name}</p>}</div>{file?.url && <a href={file.url} target="_blank" rel="noreferrer" className="whitespace-nowrap text-xs font-semibold text-green-700 hover:underline dark:text-green-400">Fullscreen ↗</a>}</div>
        <div className={`flex w-full items-center justify-center overflow-hidden bg-gray-100 dark:bg-gray-950 ${heightClass}`}>{!file ? <div className="p-8 text-center"><div className="mb-3 text-4xl" aria-hidden="true">📁</div><h4 className="text-sm font-semibold text-gray-800 dark:text-white">{emptyText}</h4><p className="mt-1 max-w-xs text-xs text-gray-500 dark:text-gray-400">Choose a PDF, image, or document attachment to view it here.</p></div> : isImage ? <img src={file.url} alt={file.name || 'Attachment preview'} className="max-h-full w-full object-contain" /> : isPdf ? <iframe src={file.url} title={file.name || 'PDF preview'} className="h-full w-full bg-white" /> : <div className="p-8 text-center"><div className="mb-3 text-5xl" aria-hidden="true">📄</div><p className="break-all text-sm font-semibold text-gray-800 dark:text-gray-200">{file.name}</p><p className="mt-2 text-xs text-gray-500">Inline preview is unavailable for this file type.</p>{file.url && <a href={file.url} target="_blank" rel="noreferrer" className="mt-4 inline-flex rounded-xl bg-green-700 px-4 py-2 text-xs font-bold text-white hover:bg-green-800">Open Document</a>}</div>}</div>
    </aside>;
}
