import { FloatingSelect, FloatingTextarea } from "@/Components/Form";import { router, useForm, usePage } from '@inertiajs/react';
import { useEffect, useRef, useState } from 'react';
import ConfirmDialog from '@/Components/ConfirmDialog';
import CrudDetailsModal from '@/Components/Crud/CrudDetailsModal';
import CrudFormModal from '@/Components/Crud/CrudFormModal';
import CrudSection from '@/Components/Crud/CrudSection';
import CrudSummaryGrid from '@/Components/Crud/CrudSummaryGrid';
import CrudTable from '@/Components/Crud/CrudTable';
import FileAttachmentPanel from '@/Components/Crud/FileAttachmentPanel';
import FilePreviewPanel from '@/Components/Crud/FilePreviewPanel';
import { useReportDetails } from '@/Components/Crud/ReportDetailsContext';
import TimelinessBadge, { isTimelinessValue } from '@/Components/TimelinessBadge';
import { formatReportValue } from '@/Utils/dateFormatters';

const empty = { protected_area_id: '', station_name: '', location: '', activity_name: '', document_type: '', semester: '1st Semester', report_period_type: 'Monthly', date_conducted: '', date_accomplished: '', start_date: '', end_date: '', status: 'Approve', recommendation_remarks: '', report_file: null };
const badgeClass = (value) => ({ 'Pending Submission by CENRO': 'bg-blue-600 text-white', 'Pending Receipt by PENRO': 'bg-blue-600 text-white', 'Pending Regional Endorsement': 'bg-blue-600 text-white', 'Completed': 'bg-green-600 text-white', 'Ongoing Preparation at CENRO Level': 'bg-blue-600 text-white', 'Report Not Yet Submitted': 'bg-red-600 text-white', 'Report Submitted': 'bg-green-600 text-white', 'No Activity Conducted': 'bg-gray-500 text-white', 'No Data': 'bg-gray-500 text-white' })[value] || 'bg-gray-500 text-white';
const Badge = ({ value }) => isTimelinessValue(value) ? <TimelinessBadge value={value} /> : <span className={`inline-flex max-w-52 whitespace-normal rounded-full px-2.5 py-1 text-xs font-bold ${badgeClass(value)}`}>{formatReportValue(value)}</span>;
const Detail = ({ label, children }) => {
  const reportDetails = useReportDetails();
  const inSummary = /^(reporting period|semester|quarter|deadline|deadline for submission to penro|timeliness(?: rating)?|submission status|status of submission|report status|number of days complied|days complied)$/i.test(label);
  if (reportDetails && inSummary) return null;
  const normalizedChildren = label === 'Date Report Released by CENRO Records' && children?.props?.value?.startsWith('Not Applicable')
    ? <Badge value="N/A — PENRO-managed PA" />
    : children;
  return <div><span className="block text-xs text-gray-500">{label}:</span><span className="font-semibold text-gray-800 dark:text-gray-200">{normalizedChildren}</span></div>;
};
const dateInput = (value) => value ? String(value).slice(0, 10) : '';

export default function AwsReportSubmissionTracker({ records = [], pagination, protectedAreas = [], filters = {} }) {
  const { auth = {} } = usePage().props;
  const [modal, setModal] = useState(null);
  const [selected, setSelected] = useState(null);
  const [preview, setPreview] = useState(null);
  const [deleting, setDeleting] = useState(null);
  const objectUrlRef = useRef(null);
  const form = useForm(empty);
  useEffect(() => {const open = () => openCreate();window.addEventListener('aws-report-create', open);return () => window.removeEventListener('aws-report-create', open);}, []);
  useEffect(() => () => {if (objectUrlRef.current) URL.revokeObjectURL(objectUrlRef.current);}, []);
  const currentFile = (report) => report?.report_file || null;
  const clearObjectUrl = () => {if (objectUrlRef.current) URL.revokeObjectURL(objectUrlRef.current);objectUrlRef.current = null;};
  const close = () => {clearObjectUrl();setModal(null);setSelected(null);setPreview(null);form.reset();form.clearErrors();};
  const openCreate = () => {close();form.setData({ ...empty, protected_area_id: protectedAreas[0]?.id || '', semester: filters.report_semester || '1st Semester' });setModal('create');};
  const openDetails = (report) => {setSelected(report);setPreview(currentFile(report));setModal('details');};
  const openEdit = (report) => {clearObjectUrl();setSelected(report);form.clearErrors();form.setData({ ...empty, ...report, protected_area_id: report.protected_area_id || '', document_type: report.document_type || report.report_period_type || '', semester: report.semester || '', date_accomplished: dateInput(report.date_accomplished), start_date: dateInput(report.start_date), end_date: dateInput(report.end_date), report_file: null });setPreview(currentFile(report));setModal('edit');};
  const openMov = (report) => {openEdit(report);setModal('mov');};
  const selectFile = (file) => {clearObjectUrl();objectUrlRef.current = file ? URL.createObjectURL(file) : null;form.setData((data) => ({ ...data, report_file: file }));setPreview(file ? { name: file.name, type: file.type, size: file.size, url: objectUrlRef.current, temporary: true } : currentFile(selected));};
  const submit = (event) => {event.preventDefault();const options = { forceFormData: true, preserveScroll: true, onSuccess: close };if (modal !== 'create') {form.transform((data) => ({ ...data, _method: 'put' }));form.post(route('aws.update', selected.id), options);} else {form.transform((data) => data);form.post(route('aws.store'), options);}};
  const visit = (changes) => router.get(route('aws.index'), { ...filters, report_search: undefined, report_document_type: undefined, tab: 'reports', reports_page: 1, ...changes }, { preserveState: true, preserveScroll: true, replace: true });
  const confirmDelete = () => router.delete(route('aws.destroy', deleting.id), { preserveScroll: true, onSuccess: () => {setDeleting(null);close();} });
  const label = 'block text-xs font-semibold text-gray-700 dark:text-gray-300';
  const error = (name) => form.errors[name] && <span className="mt-1 block text-xs text-red-500">{form.errors[name]}</span>;
  const change = (name) => (event) => form.setData(name, event.target.value);
  const columns = [
  { key: 'protected_area_name', label: 'Protected Area', render: (row) => <span className="font-semibold text-gray-900 dark:text-white">{formatReportValue(row.protected_area_name)}</span> },
  { key: 'station_name', label: 'Station / Source', render: (row) => formatReportValue(row.station_name) },
  { key: 'activity_name', label: 'Name of Activity / Report', render: (row) => <span className="block min-w-40 max-w-72 whitespace-normal">{formatReportValue(row.activity_name)}</span> },
  { key: 'document_type', label: 'Type of Document', render: (row) => formatReportValue(row.document_type) },
  { key: 'semester', label: 'Semester', render: (row) => formatReportValue(row.semester) },
  { key: 'date_conducted', label: 'Date Conducted', render: (row) => formatReportValue(row.date_conducted) },
  { key: 'date_accomplished', label: 'Date Accomplished', render: (row) => formatReportValue(row.date_accomplished) },
  { key: 'deadline_submission', label: 'Deadline', render: (row) => formatReportValue(row.deadline_submission) },
  { key: 'date_received_penro', label: 'Received by PENRO', render: (row) => formatReportValue(row.date_received_penro) },
  { key: 'number_days_complied', label: 'Days Complied', render: (row) => formatReportValue(row.number_days_complied) },
  { key: 'timeliness', label: 'Timeliness', render: (row) => <TimelinessBadge value={row.timeliness} /> },
  { key: 'submission_status', label: 'Submission Status', render: (row) => <Badge value={row.submission_status} /> }];

  const pageLinks = pagination?.links?.length > 3 ? <div className="flex flex-wrap gap-1">{pagination.links.map((link, index) => <button key={index} type="button" disabled={!link.url} onClick={() => link.url && router.get(link.url, {}, { preserveState: true, preserveScroll: true })} className={`rounded-lg px-3 py-1.5 text-xs font-bold transition ${link.active ? 'bg-green-700 text-white' : 'bg-gray-100 text-gray-600 hover:bg-green-50 dark:bg-gray-700 dark:text-gray-200'} disabled:cursor-not-allowed disabled:opacity-40`} dangerouslySetInnerHTML={{ __html: link.label }} />)}</div> : null;
  const filtersUi = <div className="grid gap-3 sm:grid-cols-2"><Filter label="Reporting Period" value={filters.report_semester || ''} onChange={(value) => visit({ report_semester: value })} options={['1st Semester', '2nd Semester'].map((value) => [value, value])} /><Filter label="Protected Area" value={filters.protected_area_id || ''} onChange={(value) => visit({ protected_area_id: value })} options={protectedAreas.map((area) => [area.id, area.name])} /></div>;

  return <div className="space-y-4">
        <CrudTable compactEmpty={true} title={records.length > 0 ? "AWS Report" : undefined} subtitle={records.length > 0 ? `${pagination?.total ?? records.length} AWS report submission${(pagination?.total ?? records.length) === 1 ? '' : 's'}` : undefined} helperText={records.length > 0 ? 'Click any row to view full details' : undefined} caption="AWS report submission tracker" columns={columns} rows={records} rowKey="id" onRowClick={openDetails} filters={filtersUi} headerActions={auth.canCreateAws && <button type="button" onClick={openCreate} className="rounded-xl bg-green-700 px-4 py-2.5 text-xs font-bold text-white shadow-sm transition hover:bg-green-800">+ Add Report</button>} pagination={records.length > 0 ? pageLinks : null} emptyTitle="No AWS report submissions found" emptyDescription="Add a report submission or adjust the selected filters." tableClassName="min-w-[2100px]" />
        <CrudDetailsModal report open={modal === 'details' && Boolean(selected)} title="AWS Report Submission Full Details" subtitle={selected ? `${selected.protected_area_name || 'No protected area'} - ${selected.station_name || 'No station'}` : ''} onClose={close} canEdit={Boolean(auth.canUpdateAws)} canDelete={Boolean(auth.canDeleteAws)} onEdit={() => openEdit(selected)} onDelete={() => setDeleting(selected)} editLabel="Edit This Submission" deleteLabel="Delete Submission" summary={selected && <CrudSummaryGrid items={[{ label: 'Semester', value: formatReportValue(selected.semester) }, { label: 'Submission Status', render: () => <Badge value={selected.submission_status} /> }, { label: 'Deadline', value: formatReportValue(selected.deadline_submission) }, { label: 'Timeliness', render: () => <Badge value={selected.timeliness} /> }]} />} attachments={selected && (currentFile(selected) ? <CrudSection title="Attachment / MOV"><div className="space-y-3"><div className="flex justify-end">{Boolean(auth.canUpdateAws) && <button type="button" onClick={() => openMov(selected)} className="rounded-xl border border-green-200 bg-green-50 px-3 py-2 text-xs font-bold text-green-700 hover:bg-green-100">Replace Attachment</button>}</div><FilePreviewPanel file={currentFile(selected)} title="Report Attachment / MOV" heightClass="h-[480px]" /></div></CrudSection> : <CrudSection title="Attachment / MOV"><p className="text-xs font-semibold text-amber-700 dark:text-amber-300">Not Yet Submitted / Missing</p>{Boolean(auth.canUpdateAws) && <button type="button" onClick={() => openMov(selected)} className="mt-3 rounded-xl bg-green-700 px-4 py-2 text-xs font-bold text-white hover:bg-green-800">Attach MOV</button>}</CrudSection>)}>
            {selected && <div className="space-y-6"><CrudSection title="Report Information"><div className="grid grid-cols-1 gap-4 text-xs sm:grid-cols-2"><Detail label="Protected Area">{formatReportValue(selected.protected_area_name)}</Detail><Detail label="Station / Source">{formatReportValue(selected.station_name)}</Detail><Detail label="Location">{formatReportValue(selected.location)}</Detail><Detail label="Activity / Report">{formatReportValue(selected.activity_name)}</Detail><Detail label="Type of Document">{formatReportValue(selected.document_type)}</Detail><Detail label="Semester">{formatReportValue(selected.semester)}</Detail><Detail label="Date Conducted">{formatReportValue(selected.date_conducted)}</Detail></div></CrudSection><CrudSection title="Compliance"><div className="grid grid-cols-1 gap-4 text-xs sm:grid-cols-2"><Detail label="Date Accomplished">{formatReportValue(selected.date_accomplished)}</Detail><Detail label="Deadline for Submission to PENRO">{formatReportValue(selected.deadline_submission)}</Detail><Detail label="Number of Days Complied">{formatReportValue(selected.number_days_complied)}</Detail><Detail label="Timeliness Rating"><Badge value={selected.timeliness} /></Detail><Detail label="Submission Status"><Badge value={selected.submission_status} /></Detail></div></CrudSection><CrudSection title="Submission Timeline"><div className="grid grid-cols-1 gap-4 text-xs sm:grid-cols-2"><Detail label="Date Report Released by CENRO Records">{selected.cenro_release_applicable === false ? <Badge value="Not Applicable \u2014 PENRO-managed Protected Area" /> : formatReportValue(selected.date_report_released_cenro)}</Detail><Detail label="Date Received by PENRO Records">{formatReportValue(selected.date_received_penro)}</Detail><Detail label="Regional Endorsement">{selected.cenro_release_applicable === false ? (!selected.date_received_penro ? <Badge value="Not Yet Available" /> : !selected.date_endorsed_regional ? <Badge value="For Endorsement" /> : formatReportValue(selected.date_endorsed_regional)) : (!selected.date_report_released_cenro ? <Badge value="Not Yet Available" /> : selected.date_received_penro && !selected.date_endorsed_regional ? <Badge value="For Endorsement" /> : formatReportValue(selected.date_endorsed_regional))}</Detail><Detail label="Total Number of Days Delayed at PENRO">{formatReportValue(selected.total_days_delayed_penro)}</Detail></div></CrudSection><CrudSection title="Remarks"><p className="whitespace-pre-wrap text-xs text-gray-800 dark:text-gray-200">{selected.recommendation_remarks || 'None.'}</p></CrudSection></div>}
        </CrudDetailsModal>
        <CrudFormModal open={modal === 'create' || modal === 'edit'} mode={modal === 'edit' ? 'edit' : 'create'} title={modal === 'edit' ? 'Edit AWS Report Submission' : 'Add AWS Report Submission'} subtitle="General/Other Reports 7-working-day submission standard." onClose={close} onSubmit={submit} processing={form.processing} errors={form.errors} saveLabel={modal === 'edit' ? 'Update Report' : 'Save Report'} preview={<FilePreviewPanel file={preview} title="Live Document Preview" />}>
            <CrudSection title="General / Report Information"><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><div className={label}><FloatingSelect id="awsreportsubmissiontracker-protected-area" label="Protected Area" required value={form.data.protected_area_id} onChange={change('protected_area_id')}><option value="">Select Protected Area</option>{protectedAreas.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</FloatingSelect>{error('protected_area_id')}</div><Field label="Station / Report Source" name="station_name" form={form} required /><Field label="Location" name="location" form={form} required /><Field label="Name of Activity / Report" name="activity_name" form={form} /><div className={label}><FloatingSelect id="awsreportsubmissiontracker-type-of-document" label="Type of Document" required value={form.data.document_type || ''} onChange={change('document_type')}><option value="">Select Type of Document</option>{form.data.document_type && !['Final Report', 'Progress Report'].includes(form.data.document_type) && <option value={form.data.document_type}>{form.data.document_type} (Legacy)</option>}<option>Final Report</option><option>Progress Report</option></FloatingSelect>{error('document_type')}</div><div className={label}><FloatingSelect id="awsreportsubmissiontracker-semester" label="Semester" required value={form.data.semester || ''} onChange={change('semester')}><option value="">Select Semester</option><option>1st Semester</option><option>2nd Semester</option></FloatingSelect>{error('semester')}</div><Field label="Date Conducted / Coverage" name="date_conducted" form={form} /><div className={label}><FloatingSelect id="awsreportsubmissiontracker-reporting-frequency" label="Reporting Frequency" required value={form.data.report_period_type} onChange={change('report_period_type')}><option>Monthly</option><option>Quarterly</option><option>Semestral</option><option>Daily</option></FloatingSelect>{error('report_period_type')}</div></div></CrudSection>
            <CrudSection title="Compliance Basis"><Field label="Date Accomplished" name="date_accomplished" type="date" form={form} /></CrudSection>
            <CrudSection title="Attachment / MOV & Remarks"><div className="space-y-5"><FileAttachmentPanel id="aws-report-form-file" label="Report Attachment / MOV" required={modal === 'create'} accept=".pdf,.jpg,.jpeg,.png,.doc,.docx,.xls,.xlsx" acceptedTypesHint="PDF, JPG, PNG, DOC, DOCX, XLS, or XLSX" maxSizeHint="Maximum 10 MB" existingFiles={currentFile(selected) ? [currentFile(selected)] : []} selectedFiles={form.data.report_file ? [form.data.report_file] : []} activeFile={preview} onSelectFile={setPreview} onChange={selectFile} error={form.errors.report_file} disabled={form.processing} canManage /><div className={label}><FloatingTextarea id="awsreportsubmissiontracker-recommendation-remarks" label="Remarks" rows="4" value={form.data.recommendation_remarks || ''} onChange={change('recommendation_remarks')} />{error('recommendation_remarks')}</div></div></CrudSection>
        </CrudFormModal>
        <CrudFormModal open={modal === 'mov'} mode="edit" title={currentFile(selected) ? 'Replace Attachment' : 'Attach MOV'} subtitle="Attach or replace the report attachment / MOV." onClose={close} onSubmit={submit} processing={form.processing} errors={form.errors} saveLabel={currentFile(selected) ? 'Replace Attachment' : 'Attach MOV'} maxWidth="max-w-xl">
            <CrudSection title="Attachment / MOV"><FileAttachmentPanel id="aws-report-mov" label="Report Attachment / MOV" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx,.xls,.xlsx" acceptedTypesHint="PDF, JPG, PNG, DOC, DOCX, XLS, or XLSX" maxSizeHint="Maximum 10 MB" existingFiles={currentFile(selected) ? [currentFile(selected)] : []} selectedFiles={form.data.report_file ? [form.data.report_file] : []} activeFile={preview} onSelectFile={setPreview} onChange={selectFile} error={form.errors.report_file} disabled={form.processing} canManage /></CrudSection>
        </CrudFormModal>
        <ConfirmDialog open={Boolean(deleting)} variant="danger" title="Delete AWS Report Submission?" message={`Delete ${deleting?.activity_name || deleting?.station_name || 'this report'}? This cannot be undone.`} confirmLabel="Delete Record" onConfirm={confirmDelete} onCancel={() => setDeleting(null)} />
    </div>;
}

function Field({ label, name, type = 'text', form, required = false }) {return <FloatingInput id={'aws-' + name} label={label} required={required} type={type} value={form.data[name] || ''} onChange={(event) => form.setData(name, event.target.value)} error={form.errors[name]} />;}
function Filter({ label, value, onChange, options }) {return <FloatingSelect id={`aws-filter-${label.toLowerCase().replace(/\s+/g, '-')}`} label={label} size="sm" value={value} onChange={(event) => onChange(event.target.value)}><option value="">All</option>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</FloatingSelect>;}
