import { Icon } from '@iconify/react';
import { router } from '@inertiajs/react';
import SettingsShell from '@/Components/Admin/SettingsShell';
import SettingsPageHeader from '@/Components/Admin/SettingsPageHeader';

const providerLabel = key => key === 'google_drive' ? 'Google Drive' : 'Server Storage';
const statusLabel = item => item.status === 'available' ? (item.provider === 'google_drive' ? 'Connected' : 'Online') : 'Capacity Unavailable';
const tone = item => item.status !== 'available' ? 'border-amber-200 bg-amber-50/60 dark:border-amber-900 dark:bg-amber-950/20' : (item.used_percentage >= 90 ? 'border-red-200 bg-red-50/50 dark:border-red-900 dark:bg-red-950/20' : item.used_percentage >= 80 ? 'border-amber-200 bg-amber-50/40 dark:border-amber-900 dark:bg-amber-950/20' : 'border-gray-200 bg-white dark:border-gray-800 dark:bg-gray-900');
const bar = item => item.status !== 'available' ? 'bg-amber-500' : item.used_percentage >= 90 ? 'bg-red-600' : item.used_percentage >= 80 ? 'bg-amber-500' : 'bg-green-600';

function ProviderPanel({ item }) {
    const percent = Number.isFinite(Number(item.used_percentage)) ? Math.max(0, Math.min(100, Number(item.used_percentage))) : 0;
    return <article className={`rounded-2xl border p-5 ${tone(item)}`}><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-300"><Icon icon={item.provider === 'google_drive' ? 'lucide:cloud' : 'lucide:server'} width="18" height="18" aria-hidden="true" /></span><div><h3 className="text-sm font-extrabold text-gray-900 dark:text-white">{providerLabel(item.provider)}</h3><p className="mt-0.5 text-[11px] text-gray-500 dark:text-gray-400">{item.source === 'local_filesystem' ? 'Filesystem capacity' : 'Connected provider'}</p></div></div><span className="inline-flex items-center gap-1.5 text-xs font-bold text-gray-700 dark:text-gray-200"><span className={`h-2 w-2 rounded-full ${item.status === 'available' ? 'bg-emerald-500' : 'bg-amber-500'}`} />{statusLabel(item)}</span></div><div className="mt-5 flex items-end justify-between gap-4"><div><p className="text-2xl font-extrabold tracking-tight text-gray-900 dark:text-white">{item.used_label || 'Not reported'} <span className="text-sm font-semibold text-gray-500">used</span></p><p className="mt-1 text-xs text-gray-500 dark:text-gray-400">{item.free_label ? `${item.free_label} available` : 'Free capacity not reported'}</p></div><p className="text-lg font-extrabold text-gray-800 dark:text-gray-200">{item.used_percentage == null ? '—' : `${item.used_percentage}%`}</p></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-gray-200 dark:bg-gray-800"><div className={`h-full rounded-full ${bar(item)}`} style={{ width: `${percent}%` }} /></div><div className="mt-3 flex flex-wrap justify-between gap-2 text-[11px] text-gray-500 dark:text-gray-400"><span>{item.total_label ? `${item.total_label} total` : 'Capacity limit not reported'}</span><span>{item.measured_at ? `Measured ${new Date(item.measured_at).toLocaleString()}` : 'Not measured'}</span></div>{item.message && <p className="mt-3 text-xs leading-5 text-gray-500 dark:text-gray-400">{item.message}</p>}</article>;
}

export default function Storage({ capacity }) {
    const providers = capacity ? capacity.providers || {} : {};
    return <SettingsShell active="Storage">
        <SettingsPageHeader title="Storage" description="Monitor application and cloud storage capacity." actions={<button type="button" onClick={() => router.post('/settings/storage/refresh', {}, { preserveScroll: true })} className="inline-flex items-center gap-2 rounded-lg border border-gray-300 px-3 py-2 text-xs font-bold text-gray-700 hover:border-green-600 hover:text-green-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-green-600 focus-visible:ring-offset-2 dark:border-gray-700 dark:text-gray-200 dark:hover:border-green-400 dark:hover:text-green-300 dark:focus-visible:ring-offset-gray-900" data-cds-action="true" data-cds-action-variant="primary"><Icon icon="lucide:refresh-cw" width="14" height="14" aria-hidden="true" /> Refresh</button>} />
        <p className="text-xs leading-5 text-gray-500 dark:text-gray-400">Capacity values are retrieved automatically from the configured storage providers. Cached for {Math.round((capacity?.cache_seconds || 600) / 60)} minutes.</p>
        <p className="mt-2 text-xs leading-5 text-gray-600 dark:text-gray-300">Google Drive archive root: <span className="font-semibold text-gray-800 dark:text-gray-100">CDS-SMART Final Reports</span>. Capacity quota is reported separately and may be unavailable.</p>
        <div className="mt-5 grid gap-4 xl:grid-cols-2"><ProviderPanel item={providers.server || { provider: 'server', status: 'unavailable', source: 'runtime_unavailable' }} /><ProviderPanel item={providers.google_drive || { provider: 'google_drive', status: 'unavailable', source: 'provider_unavailable' }} /></div>
    </SettingsShell>;
}
