import { Head, router } from '@inertiajs/react';
import { useMemo, useState } from 'react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import PageHeader from '@/Components/PageHeader';
import Card from '@/Components/Card';
import StatusBadge from '@/Components/StatusBadge';

const titles = {
    'application.environment': 'Application Environment', 'application.runtime': 'System Runtime', 'application.debug': 'Debug Mode', 'frontend.manifest': 'Frontend Build',
    'database.connection': 'Database Connection', 'database.migrations': 'Database Migrations', 'cache.configuration': 'Cache Service', 'session.configuration': 'Session Management',
    'storage.private': 'Private File Storage', 'mail.readiness': 'Email Configuration', 'queue.configuration': 'Background Queue', 'scheduler.configuration': 'Scheduled Tasks',
    'logging.configuration': 'Application Logging', 'security.https': 'HTTPS Security', 'security.session_cookie': 'Secure Session Cookie', 'security.http_only_cookie': 'HTTP-Only Cookie', 'security.same_site_cookie': 'SameSite Cookie Protection',
};
const statusVariant = { pass: 'active', warning: 'pending', fail: 'inactive', not_verified: 'info' };
const statusLabel = { pass: 'Passed', warning: 'Needs Attention', fail: 'Failed', not_verified: 'Not Verified' };
const healthMessage = { healthy: 'All verified system checks are operating normally.', warning: 'The system is operational, but some settings need attention or cannot be fully verified.', critical: 'One or more important system checks failed and should be reviewed.' };
const explanation = {
    'application.environment': 'Shows which application environment is currently active.', 'application.runtime': 'Confirms the application runtime versions and timezone are available.', 'application.debug': 'Debug mode controls how much diagnostic information the application exposes.', 'frontend.manifest': 'Confirms that the built frontend assets can be loaded.',
    'database.connection': 'The application successfully connected to the database.', 'database.migrations': 'Confirms whether the database structure is up to date.', 'cache.configuration': 'The cache configuration is readable, but Phase 1 does not write test data to confirm cache storage.', 'session.configuration': 'Checks whether the configured session management is available without reading session data.',
    'storage.private': 'Checks whether the configured private file storage is readable without writing a test file.', 'mail.readiness': 'Required email settings are configured. No test email was sent.', 'queue.configuration': 'Shows whether background work is synchronous or configured for an asynchronous queue.', 'scheduler.configuration': 'Scheduled commands are registered, but the system does not yet track their most recent execution.', 'logging.configuration': 'Confirms that the default application logging channel is configured.',
    'security.https': 'HTTPS is not expected in this local environment, so secure web transport cannot be verified here.', 'security.session_cookie': 'Secure cookies help prevent session data from being sent over an unencrypted connection.', 'security.http_only_cookie': 'HTTP-only cookies prevent browser scripts from reading the session cookie.', 'security.same_site_cookie': 'SameSite limits when browsers send session cookies across sites.',
};
const recommendation = { 'application.debug': 'Set APP_DEBUG=false before production deployment.', 'frontend.manifest': 'Run the frontend production build before serving the application.', 'database.migrations': 'Review pending migrations and apply them through the normal deployment process.', 'cache.configuration': 'Verify the configured cache store in the deployment environment.', 'storage.private': 'Verify that the configured private storage location exists and is readable.', 'mail.readiness': 'Configure the sender address before enabling email delivery.', 'scheduler.configuration': 'Review the scheduler configuration and deployment heartbeat separately.', 'security.https': 'Verify HTTPS and trusted proxy behavior on the live deployment.', 'security.session_cookie': 'Enable secure session cookies for an HTTPS production deployment.', 'security.http_only_cookie': 'Enable HTTP-only session cookies.', 'security.same_site_cookie': 'Use a deliberate SameSite policy appropriate for the deployment.' };

export default function SystemDiagnostics({ diagnostics }) {
    const [running, setRunning] = useState(false); const [complete, setComplete] = useState(false); const [error, setError] = useState(''); const [expanded, setExpanded] = useState({});
    const data = diagnostics || { groups: {}, checks: [], summary: {}, overall: 'warning' };
    const snapshot = useMemo(() => JSON.stringify(data.snapshot || {}, null, 2), [data.snapshot]);
    const run = () => { setRunning(true); setComplete(false); setError(''); router.reload({ only: ['diagnostics'], onSuccess: () => setComplete(true), onError: () => setError('Diagnostics could not be refreshed. The previous results remain visible.'), onFinish: () => setRunning(false) }); };
    const copy = async () => { await navigator.clipboard?.writeText(snapshot); };
    const groups = Object.entries(data.groups || {}).map(([group, checks]) => [group, checks.filter(check => !(group === 'SYSTEM HEALTH' && check.check === 'application.debug'))]).filter(([, checks]) => checks.length);
    return <AuthenticatedLayout title="System Diagnostics"><Head title="System Diagnostics" /><PageHeader title="System Diagnostics" description="Monitor application health, runtime configuration, and core service readiness." actions={<div className="flex flex-wrap gap-2"><button type="button" onClick={run} disabled={running} className="rounded-lg bg-green-700 px-4 py-2 text-xs font-bold text-white disabled:opacity-50">{running ? 'Running Diagnostics...' : 'Run Diagnostics'}</button><button type="button" onClick={copy} className="rounded-lg border border-green-700 px-4 py-2 text-xs font-bold text-green-700 dark:text-green-300">Copy Diagnostic Snapshot</button></div>} />
        {running && <div className="mt-4 rounded-xl border border-blue-200 bg-blue-50/70 p-4 dark:border-blue-900 dark:bg-blue-950/30"><p className="text-sm font-semibold text-blue-900 dark:text-blue-100">Running system checks...</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-blue-100 dark:bg-blue-900"><div className="h-full w-1/3 animate-pulse rounded-full bg-blue-600" /></div><p className="mt-2 text-xs text-blue-800 dark:text-blue-200">Checks run in one read-only request; exact per-check progress is not available.</p></div>}
        {complete && !running && <p className="mt-4 text-sm font-semibold text-emerald-700 dark:text-emerald-300">Diagnostics complete.</p>}{error && <p className="mt-4 rounded-lg bg-red-50 p-3 text-sm font-semibold text-red-700 dark:bg-red-950/30 dark:text-red-300" role="alert">{error}</p>}
        <div className="mt-6 grid gap-4 sm:grid-cols-3 lg:grid-cols-6">{[['Overall Health', data.overall], ['Last Checked', data.generated_at ? new Date(data.generated_at).toLocaleString() : '—'], ['Passed', data.summary.pass || 0], ['Warnings', data.summary.warning || 0], ['Failed', data.summary.fail || 0], ['Not Verified', data.summary.not_verified || 0]].map(([name, value]) => <Card key={name} padding="p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-gray-500">{name}</p><p className="mt-2 text-lg font-extrabold text-gray-900 dark:text-white">{name === 'Overall Health' ? String(value || '').toUpperCase() : value}</p>{name === 'Overall Health' && <p className="mt-2 text-xs leading-5 text-gray-600 dark:text-gray-300">{healthMessage[value] || healthMessage.warning}</p>}</Card>)}</div>
        <div className="mt-6 space-y-6">{groups.map(([group, checks]) => <section key={group}><h2 className="mb-3 text-xs font-extrabold uppercase tracking-[0.16em] text-gray-500">{group}</h2><div className="grid gap-4 lg:grid-cols-2">{checks.map(check => { const isExpanded = Boolean(expanded[check.check]); const hasDetails = Object.keys(check.details || {}).length > 0; return <Card key={check.check} padding="p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold text-gray-900 dark:text-white">{titles[check.check] || check.check}</h3><p className="mt-1 text-sm text-gray-600 dark:text-gray-300">{explanation[check.check] || check.summary}</p></div><StatusBadge variant={statusVariant[check.status] || 'info'}>{statusLabel[check.status] || 'Not Verified'}</StatusBadge></div>{check.status !== 'pass' && recommendation[check.check] && <p className="mt-3 rounded-lg bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-900 dark:bg-amber-950/30 dark:text-amber-200"><span className="font-extrabold">Recommended action:</span> {recommendation[check.check]}</p>}<div className="mt-3 text-[11px] text-gray-500">Check completed in {check.duration_ms} ms</div>{hasDetails && <div className="mt-3"><button type="button" onClick={() => setExpanded(current => ({ ...current, [check.check]: !isExpanded }))} className="text-xs font-bold text-green-700 hover:underline dark:text-green-300">{isExpanded ? 'Hide Technical Details' : 'View Technical Details'}</button>{isExpanded && <pre className="mt-2 overflow-auto rounded-lg bg-gray-50 p-3 text-[11px] text-gray-600 dark:bg-gray-800 dark:text-gray-300">{JSON.stringify(check.details, null, 2)}</pre>}</div>}</Card>; })}</div></section>)}</div>
    </AuthenticatedLayout>;
}
