import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { FloatingSelect } from '@/Components/Form';
import TimelinessBadge from '@/Components/TimelinessBadge';
import { router } from '@inertiajs/react';
import { formatReportDate } from '@/Utils/dateFormatters';
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useEffect, useState } from 'react';

const DASH = '—';
const percent = value => `${Number(value || 0).toFixed(Number(value || 0) % 1 ? 1 : 0)}%`;
const days = value => value === null || value === undefined ? DASH : `${Number(value).toFixed(1)} days`;

function Filters({ filters = {}, filterOptions = {}, tab }) {
    const [values, setValues] = useState(filters);
    useEffect(() => setValues(filters), [filters]);
    const update = (key, value) => { const { program: _program, ...tabValues } = values; const next = { ...tabValues, [key]: value, tab }; setValues(next); router.get(route('dashboard'), next, { preserveScroll: true, preserveState: true, replace: true }); };
    const field = (label, key, options, empty) => <FloatingSelect label={label} value={values[key] ?? ''} onChange={event => update(key, event.target.value)} className="min-w-0" size="compact"><option value="">{empty}</option>{options.map((item) => { const option = item !== null && typeof item === 'object' ? item : { value: item, label: item }; return <option key={option.value} value={option.value}>{option.label}</option>; })}</FloatingSelect>;
    return <section aria-label="Dashboard filters" className="grid grid-cols-1 gap-3 rounded-xl border border-slate-200 bg-white p-3 shadow-sm dark:grid-cols-3 dark:border-slate-700 dark:bg-slate-900 md:grid-cols-[minmax(0,0.8fr)_minmax(0,1fr)_minmax(0,1.6fr)]">{field('Reporting Year', 'year', filterOptions.years || [], 'All years')}{field('Frequency', 'frequency', filterOptions.frequencies || [], 'All frequencies')}{field('Source Office', 'office', filterOptions.offices || [], 'All authorized offices')}</section>;
}

function Tabs({ active, filters = {} }) {
    return <nav aria-label="Dashboard program tabs" className="grid grid-cols-2 overflow-hidden rounded-xl border border-emerald-800 bg-white shadow-sm dark:border-emerald-700 dark:bg-slate-900">{[['conservation', 'Conservation'], ['development', 'Development']].map(([tab, label]) => <button key={tab} type="button" aria-current={active === tab ? 'page' : undefined} onClick={() => router.get(route('dashboard'), { ...filters, tab }, { preserveScroll: true, preserveState: true, replace: true })} className={`px-4 py-3 text-sm font-semibold transition ${active === tab ? 'bg-emerald-800 text-white' : 'text-emerald-800 hover:bg-emerald-50 dark:text-emerald-300 dark:hover:bg-emerald-950/40'}`}>{label}</button>)}</nav>;
}

function Metric({ label, value, hint, tone = 'slate' }) {
    const tones = { slate: 'text-slate-900 dark:text-white', green: 'text-emerald-700 dark:text-emerald-400', amber: 'text-amber-700 dark:text-amber-400', red: 'text-red-700 dark:text-red-400', blue: 'text-sky-700 dark:text-sky-400' };
    return <article className="min-h-[94px] rounded-xl border border-slate-200 bg-white px-3 py-2.5 shadow-sm dark:border-slate-700 dark:bg-slate-900"><p className="text-[11px] font-medium uppercase tracking-wide text-slate-500 dark:text-slate-400">{label}</p><p className={`mt-1 text-[27px] font-semibold leading-none ${tones[tone]}`}>{value}</p><p className="mt-1 text-xs font-normal text-slate-500 dark:text-slate-400">{hint}</p></article>;
}

function ProcessStatus({ value }) { const name = String(value || 'Pending'); const lower = name.toLowerCase(); const color = lower.includes('overdue') || lower.includes('late') ? 'bg-red-50 text-red-700 dark:bg-red-950/40 dark:text-red-300' : lower.includes('progress') || lower.includes('correction') ? 'bg-sky-50 text-sky-700 dark:bg-sky-950/40 dark:text-sky-300' : lower.includes('time') || lower.includes('complete') ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300' : 'bg-amber-50 text-amber-700 dark:bg-amber-950/40 dark:text-amber-300'; return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-medium ${color}`}>{name}</span>; }
function ReportTimeliness({ value, fallback }) { return value && String(value).trim() ? <TimelinessBadge value={value} /> : <ProcessStatus value={fallback} />; }

function WorkCard({ title, items = [], overdue = false }) { return <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900"><h3 className={`border-b border-slate-200 px-4 py-3 text-sm font-semibold uppercase tracking-wide dark:border-slate-700 ${overdue ? 'text-red-700 dark:text-red-400' : 'text-slate-900 dark:text-white'}`}>{title}</h3>{items.length ? <div className="divide-y divide-slate-100 dark:divide-slate-800">{items.map(item => <a key={item.id} href={item.source_url} className="grid gap-2 px-4 py-3 transition hover:bg-slate-50 dark:hover:bg-slate-800/60 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto] sm:items-center"><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-800 dark:text-slate-100">{item.office}</p><p className="mt-0.5 truncate text-xs text-slate-500 dark:text-slate-400">{item.context}</p></div><div className="min-w-0"><p className="truncate text-sm text-slate-800 dark:text-slate-100">{item.report}</p><p className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">{item.period} · Due {formatReportDate(item.due)}</p></div>{overdue && Number.isFinite(item.days_overdue) ? <p className="text-sm font-semibold text-red-700 dark:text-red-400">{item.days_overdue} days overdue</p> : <ProcessStatus value={item.status} />}</a>)}</div> : <p className="px-4 py-8 text-center text-sm font-normal text-slate-500 dark:text-slate-400">No matching reports.</p>}</section>; }

function Comparison({ title, items = [] }) {
    const data = items.map(item => ({ office: item.office, ...Object.fromEntries(Object.entries(item.series || {}).map(([frequency, series]) => [frequency, series?.eligible ? series.rate : null])) }));
    const frequencies = [...new Set(items.flatMap(item => Object.keys(item.series || {})))];
    const colors = { Monthly: '#18835b', Quarterly: '#367f93', Annual: '#d2a337', Semestral: '#7c3aed' };
    return <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-900"><h3 className="text-sm font-semibold uppercase tracking-wide text-slate-900 dark:text-white">{title}</h3><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">On-time submission rate by office and reporting frequency (%)</p>{data.length && frequencies.length ? <><div className="mt-3 h-72 min-w-0 overflow-x-auto"><div className="h-full min-w-[560px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{ top: 16, right: 8, left: 0, bottom: 30 }}><CartesianGrid stroke="#dce6df" vertical={false} /><XAxis dataKey="office" interval={0} angle={data.length > 5 ? -25 : 0} textAnchor={data.length > 5 ? 'end' : 'middle'} height={data.length > 5 ? 55 : 30} tick={{ fill: '#52665e', fontSize: 11, fontWeight: 500 }} /><YAxis domain={[0, 100]} tick={{ fill: '#718078', fontSize: 11 }} tickLine={false} axisLine={false} tickFormatter={value => `${value}%`} /><Tooltip formatter={(value, name) => [value === null ? 'No eligible data' : `${value}%`, name]} contentStyle={{ border: '1px solid #d8e4dc', borderRadius: 8, fontSize: 12 }} /><Legend wrapperStyle={{ fontSize: 12 }} />{frequencies.map(frequency => <Bar key={frequency} dataKey={frequency} name={frequency} fill={colors[frequency] || '#64748b'} radius={[4, 4, 0, 0]} />)}</BarChart></ResponsiveContainer></div></div></> : <p className="py-12 text-center text-sm text-slate-500 dark:text-slate-400">No comparable eligible reports for the selected filters.</p>}</section>;
}

function TimelinessSummary({ title, rows = [] }) { return <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900"><h3 className="px-4 pt-4 text-sm font-semibold uppercase tracking-wide text-slate-900 dark:text-white">{title}</h3><div className="overflow-x-auto"><table className="mt-3 min-w-full text-left text-sm"><thead className="bg-slate-50 text-[11px] font-medium uppercase tracking-wide text-slate-600 dark:bg-slate-800 dark:text-slate-300"><tr><th className="px-4 py-2">Frequency</th><th className="px-4 py-2">Most timely office</th><th className="px-4 py-2">Office needing follow-up</th></tr></thead><tbody>{rows.length ? rows.map(row => <tr key={row.frequency} className="border-t border-slate-100 dark:border-slate-800"><td className="px-4 py-3 font-medium">{row.frequency}</td><td className="px-4 py-3 text-emerald-700 dark:text-emerald-400">{row.most_timely ? `${row.most_timely.office} · ${percent(row.most_timely.rate)} (${row.most_timely.eligible})` : 'Insufficient data'}</td><td className="px-4 py-3 text-red-700 dark:text-red-400">{row.needs_follow_up ? `${row.needs_follow_up.office} · ${percent(row.needs_follow_up.rate)} (${row.needs_follow_up.eligible})` : 'Insufficient data'}</td></tr>) : <tr><td colSpan="3" className="px-4 py-8 text-center text-slate-500">Insufficient data.</td></tr>}</tbody></table></div></section>; }

function TrackingTable({ rows = [], total = 0, tab }) { return <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900"><div className="px-4 py-4"><h2 className="text-lg font-semibold uppercase tracking-wide text-slate-900 dark:text-white">All {tab === 'development' ? 'Development' : 'Conservation'} Report Submissions</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{total} authorized normalized records. Select a row to open it in Submission Tracking.</p></div><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-emerald-50 text-[11px] font-medium uppercase tracking-wide text-emerald-950 dark:bg-emerald-950/30 dark:text-emerald-100"><tr>{['Source Office','Report / Period','Due','Received','Process Status','Timeliness','Days','Next Action'].map(label => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{rows.length ? rows.map(row => <tr key={row.id} className="border-t border-slate-100 transition hover:bg-slate-50 dark:border-slate-800 dark:hover:bg-slate-800/60"><td className="px-4 py-3">{row.office}</td><td className="px-4 py-3"><a className="font-medium text-emerald-800 hover:underline dark:text-emerald-300" href={row.source_url}>{row.report}</a><p className="mt-0.5 text-xs text-slate-500">{row.period}</p></td><td className="px-4 py-3">{formatReportDate(row.due)}</td><td className="px-4 py-3">{formatReportDate(row.received)}</td><td className="px-4 py-3"><ProcessStatus value={row.status} /></td><td className="px-4 py-3"><ReportTimeliness value={row.timeliness} fallback={row.status} /></td><td className="px-4 py-3 font-medium">{row.days}</td><td className="px-4 py-3">{row.next_action}</td></tr>) : <tr><td colSpan="8" className="px-4 py-12 text-center text-slate-500">No report submissions match the selected filters.</td></tr>}</tbody></table></div></section>; }

function Program({ program, tab }) { const metrics = program.metrics || {}; const label = tab === 'development' ? 'DEVELOPMENT REPORTS' : 'CONSERVATION REPORTS'; const office = tab === 'development' ? 'CENROs' : 'PAMOs / PA Offices'; return <section className="space-y-4"><div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 dark:border-emerald-800 dark:bg-emerald-950/30"><h2 className="text-lg font-semibold text-emerald-950 dark:text-emerald-100">{label} <span className="mx-2 text-emerald-500">|</span> {office}</h2><p className="text-sm font-normal text-emerald-800/70 dark:text-emerald-200/70">{program.office_count || 0} authorized office{program.office_count === 1 ? '' : 's'} in the selected scope</p></div><div className="grid grid-cols-2 gap-3 lg:grid-cols-3"><Metric label="Pending" value={metrics.pending ?? 0} hint="not yet started" tone="amber" /><Metric label="In Progress" value={metrics.in_progress ?? 0} hint="active routing or correction" tone="blue" /><Metric label="Overdue" value={metrics.overdue ?? 0} hint="still unreceived" tone="red" /><Metric label="On Time" value={percent(metrics.on_time_rate)} hint="eligible received reports" tone="green" /><Metric label="Average Early" value={days(metrics.average_early)} hint="early receipts" tone="green" /><Metric label="Average Late" value={days(metrics.average_late)} hint="late receipts" tone="red" /></div><WorkCard title="Pending and Ongoing Submissions" items={program.pending_ongoing} /><WorkCard title="Overdue and Still Unreceived" items={program.overdue_unreceived} overdue /><Comparison title={tab === 'development' ? 'CENRO Submission Comparison' : 'PAMO Submission Comparison'} items={program.comparison} /><TimelinessSummary title={tab === 'development' ? 'CENRO | Timeliness Summary' : 'PAMO | Timeliness Summary'} rows={program.timeliness_summary} /></section>; }

function DevelopmentDashboard({ data = {} }) {
    const summary = data.summary || {};
    const rows = data.rows || [];
    const total = data.pagination?.total ?? summary.expected ?? 0;
    const workItems = (items) => items.map((row) => ({
        id: row.id,
        source_url: row.source_url,
        office: row.office,
        context: `${row.frequency} · ${row.reporting_period}`,
        report: row.report,
        period: row.reporting_period,
        due: row.deadline,
        status: row.monitoring_status,
        days_overdue: '—',
    }));

    return <section className="space-y-4">
        <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 dark:border-emerald-800 dark:bg-emerald-950/30">
            <h2 className="text-lg font-semibold text-emerald-950 dark:text-emerald-100">DEVELOPMENT REPORTS <span className="mx-2 text-emerald-500">|</span> CENROs</h2>
            <p className="text-sm font-normal text-emerald-800/70 dark:text-emerald-200/70">{data.filterOptions?.offices?.length || 0} authorized office{data.filterOptions?.offices?.length === 1 ? '' : 's'} · {total} scheduled requirement{total === 1 ? '' : 's'}</p>
        </div>
        <div className="grid grid-cols-2 gap-3 lg:grid-cols-3">
            <Metric label="Scheduled Requirements" value={summary.expected ?? 0} hint="active registry obligations" />
            <Metric label="Pending Preparation" value={summary.within_preparation_period ?? 0} hint="within preparation period" tone="amber" />
            <Metric label="Ongoing Preparation" value={summary.ongoing_preparation ?? 0} hint="approaching deadline" tone="blue" />
            <Metric label="Overdue" value={summary.overdue ?? 0} hint="not yet received by PENRO" tone="red" />
            <Metric label="Submitted" value={summary.submitted ?? 0} hint="official PENRO receipt recorded" tone="green" />
            <Metric label="Compliance Rate" value={percent(summary.compliance_rate)} hint="submitted / scheduled" tone="green" />
        </div>
        <WorkCard title="Pending and Ongoing Requirements" items={workItems(rows.filter((row) => row.pending && !row.submitted))} />
        <WorkCard title="Overdue and Not Yet Submitted" items={workItems(rows.filter((row) => row.overdue))} overdue />
        <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900">
            <div className="px-4 py-4"><h2 className="text-lg font-semibold uppercase tracking-wide text-slate-900 dark:text-white">All Development Requirements</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Showing {rows.length} of {total} authorized scheduled requirements. Select a row to open its report workflow.</p></div>
            <div className="overflow-x-auto"><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-emerald-50 text-[11px] font-medium uppercase tracking-wide text-emerald-950 dark:bg-emerald-950/30 dark:text-emerald-100"><tr>{['Source Office', 'Report / Period', 'Deadline', 'PENRO Receipt', 'Monitoring Status', 'Submission Record'].map((label) => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id} className="border-t border-slate-100 transition hover:bg-slate-50 dark:border-slate-800 dark:hover:bg-slate-800/60"><td className="px-4 py-3">{row.office}</td><td className="px-4 py-3"><a className="font-medium text-emerald-800 hover:underline dark:text-emerald-300" href={row.source_url}>{row.report}</a><p className="mt-0.5 text-xs text-slate-500">{row.frequency} · {row.reporting_period}</p></td><td className="px-4 py-3">{formatReportDate(row.deadline)}</td><td className="px-4 py-3">{formatReportDate(row.date_received)}</td><td className="px-4 py-3"><ProcessStatus value={row.monitoring_status} /></td><td className="px-4 py-3">{row.record_source}</td></tr>) : <tr><td colSpan="6" className="px-4 py-12 text-center text-slate-500">No scheduled requirements match the selected filters.</td></tr>}</tbody></table></div>
        </section>
        <section className="grid gap-4 lg:grid-cols-2">
            {[['Requirements by CENRO', data.officePerformance || [], 'office'], ['Requirements by Report Type', data.reportTypeCompliance || [], 'label']].map(([title, items, key]) => <div key={title} className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900"><h3 className="px-4 py-3 text-sm font-semibold uppercase tracking-wide">{title}</h3><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase"><tr><th className="px-4 py-2">{title.includes('CENRO') ? 'Office' : 'Report Type'}</th><th className="px-4 py-2">Expected</th><th className="px-4 py-2">Submitted</th><th className="px-4 py-2">Overdue</th></tr></thead><tbody>{items.length ? items.map((item) => <tr key={item[key]} className="border-t border-slate-100 dark:border-slate-800"><td className="px-4 py-2">{item[key]}</td><td className="px-4 py-2">{item.expected}</td><td className="px-4 py-2">{item.submitted}</td><td className="px-4 py-2">{item.overdue}</td></tr>) : <tr><td colSpan="4" className="px-4 py-6 text-center text-slate-500">No matching requirements.</td></tr>}</tbody></table></div></div>)}
        </section>
    </section>;
}

export default function Dashboard({ dashboard = {}, engp = {} }) {
    const tab = dashboard.tab === 'development' ? 'development' : 'conservation';
    const program = (dashboard.programs || []).find((item) => item.key === 'pa') || { metrics: {}, pending_ongoing: [], overdue_unreceived: [], comparison: [], timeliness_summary: [], office_count: 0 };
    const filters = tab === 'development' ? engp.filters || {} : dashboard.filters || {};
    const filterOptions = tab === 'development' ? engp.filterOptions || {} : dashboard.filterOptions || {};
    const { program: _program, ...tabFilters } = filters;

    return <AuthenticatedLayout title="CDS-SMART | Report Submission Overview"><main className="space-y-5 pb-6"><section className="rounded-xl bg-[#0f4d3b] px-5 py-6 text-white shadow-sm sm:px-7 sm:py-8"><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">Report Submission Overview</h1><p className="mt-3 text-lg font-normal text-emerald-50/90">See every pending, ongoing, overdue, on-time, and late report in one place.</p><div className="mt-3 flex flex-col gap-2 text-sm font-normal text-emerald-100 sm:flex-row sm:justify-between"><span>Conservation submissions from PAMOs <span className="mx-2 hidden sm:inline">|</span> Development submissions from CENROs</span><span>Status as of {formatReportDate(dashboard.as_of)}</span></div></section><Filters tab={tab} filters={filters} filterOptions={filterOptions} /><Tabs active={tab} filters={{ ...tabFilters, tab }} />{tab === 'development' ? <DevelopmentDashboard data={engp} /> : <><Program program={program} tab="conservation" /><TrackingTable rows={dashboard.trackingRows} total={dashboard.trackingTotal} tab="conservation" /></>}<footer className="px-1"><h2 className="text-sm font-semibold uppercase tracking-wide text-emerald-950 dark:text-emerald-300">How Days Are Counted</h2><p className="mt-1 text-sm font-normal text-slate-600 dark:text-slate-300">Days early = deadline minus verified official receipt date. Days late = verified official receipt date minus deadline. Days overdue = as-of date minus deadline while officially unreceived. A report received on its deadline is on time, 0 days early.</p></footer></main></AuthenticatedLayout>;
}
