import PageHeader from '@/Components/PageHeader';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Icon } from '@iconify/react';
import { router } from '@inertiajs/react';

const filters = [['all', 'All'], ['unread', 'Unread'], ['overdue', 'Overdue'], ['due_soon', 'Due Soon'], ['submission_updates', 'Submission Updates']];
const tone = severity => severity === 'danger' ? 'text-red-600 dark:text-red-400' : severity === 'warning' ? 'text-amber-600 dark:text-amber-400' : severity === 'success' ? 'text-green-600 dark:text-green-400' : 'text-blue-600 dark:text-blue-400';
const icon = severity => severity === 'danger' ? 'solar:danger-triangle-bold' : severity === 'warning' ? 'solar:clock-circle-bold' : severity === 'success' ? 'solar:check-circle-bold' : 'solar:bell-bing-bold';

export default function NotificationsIndex({ notifications, filter }) {
    const csrf = () => document.querySelector('meta[name="csrf-token"]')?.getAttribute('content') || '';
    const update = (url, method = 'PATCH', destination = null) => router.visit(url, { method: method.toLowerCase(), preserveScroll: true, data: {}, headers: { 'X-CSRF-TOKEN': csrf() }, onSuccess: () => destination && router.visit(destination) });
    return <AuthenticatedLayout title="Notifications"><div className="space-y-6"><PageHeader title="Notifications" description="System alerts, report deadlines, and submission updates" actions={<button type="button" onClick={() => update('/notifications/read-all', 'POST')} className="rounded-lg bg-white/15 px-3 py-2 text-sm font-semibold hover:bg-white/25">Mark all as read</button>} /><div className="flex flex-wrap gap-2">{filters.map(([value, label]) => <button key={value} type="button" onClick={() => router.get('/notifications', { filter: value }, { preserveState: true, preserveScroll: true, replace: true })} className={`rounded-full px-3 py-1.5 text-sm font-semibold ${filter === value ? 'bg-green-700 text-white dark:bg-green-600' : 'bg-white text-gray-600 shadow-sm dark:bg-gray-900 dark:text-gray-300'}`}>{label}</button>)}</div><section className="overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-900">{notifications.length ? notifications.map(notification => <div key={notification.id} className={`flex gap-4 border-b border-gray-100 px-5 py-4 last:border-0 dark:border-gray-800 ${!notification.read_at ? 'bg-green-50/60 dark:bg-green-950/20' : ''}`}><Icon icon={icon(notification.severity)} width="22" height="22" className={`mt-0.5 shrink-0 ${tone(notification.severity)}`} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><h2 className="font-semibold text-gray-900 dark:text-white">{notification.title}</h2><p className="mt-1 text-sm text-gray-600 dark:text-gray-300">{notification.message}</p><p className="mt-2 text-xs text-gray-500">{notification.source_label}{notification.office ? ` · ${notification.office}` : ''}</p></div>{!notification.read_at && <span className="rounded-full bg-red-100 px-2 py-1 text-xs font-semibold text-red-700 dark:bg-red-950/50 dark:text-red-300">Unread</span>}</div><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={() => update(`/notifications/${notification.id}/${notification.read_at ? 'unread' : 'read'}`)} className="rounded-lg border border-gray-200 px-2.5 py-1.5 text-xs font-semibold text-gray-700 dark:border-gray-700 dark:text-gray-200">Mark as {notification.read_at ? 'unread' : 'read'}</button>{notification.url && <button type="button" onClick={() => update(`/notifications/${notification.id}/read`, 'PATCH', notification.url)} className="rounded-lg bg-green-700 px-2.5 py-1.5 text-xs font-semibold text-white">View</button>}</div></div></div>) : <div className="px-6 py-12 text-center text-sm text-gray-500">No notifications match this filter.</div>}</section></div></AuthenticatedLayout>;
}
