import { FloatingInput, FloatingSelect, FloatingTextarea } from "@/Components/Form";import { useForm } from '@inertiajs/react';
import CrudFormModal from '@/Components/Crud/CrudFormModal';
import CrudSection from '@/Components/Crud/CrudSection';
import { formatReportDate } from '@/Utils/dateFormatters';
import ProfileDocuments, { useProfileDocuments } from './ProfileDocuments';

export const CHECKLIST = {
  executive_summary: 'Executive Summary', protected_area_description: 'Protected Area Description', maps_spatial_information: 'Maps / Spatial Information', situational_analysis: 'Situational Analysis', vision_goals_objectives: 'Vision, Goals & Objectives', management_strategies_activities: 'Management Strategies / Activities', human_resources_institutional_arrangement: 'Human Resources & Institutional Arrangement', financial_plan: 'Financial Plan', monitoring_evaluation_indicators: 'Monitoring & Evaluation Indicators'
};
const show = (value) => value === null || value === undefined || value === '' ? '—' : value;
const yesNo = (value) => value === null || value === undefined ? '—' : value ? 'Yes' : 'No';
const period = (profile) => profile.planning_period_start || profile.planning_period_end ? `${show(profile.planning_period_start)}–${show(profile.planning_period_end)}` : '—';
const completeness = (profile) => `${profile.completeness_completed || 0} / ${profile.completeness_total || 9} Complete`;
const Detail = ({ label, children }) => <div><span className="block text-xs text-gray-500">{label}:</span><span className="font-semibold text-gray-800 dark:text-gray-200">{children}</span></div>;

export function ProfileFormModal({ profile, selectedPlanType, protectedAreas, approvalStatuses, documentCategories, onClose }) {
  const isEdit = Boolean(profile);
  const emptyChecklist = Object.fromEntries(Object.keys(CHECKLIST).map((key) => [key, false]));
  const form = useForm({ protected_area_id: profile?.protected_area_id || '', planning_period_start: profile?.planning_period_start || '', planning_period_end: profile?.planning_period_end || '', lead_office: profile?.lead_office || '', lead_preparer: profile?.lead_preparer || '', date_preparation_started: profile?.date_preparation_started || '', twg_constituted: profile?.twg_constituted === null || profile?.twg_constituted === undefined ? '' : profile.twg_constituted ? '1' : '0', stakeholder_consultation_conducted: profile?.stakeholder_consultation_conducted === null || profile?.stakeholder_consultation_conducted === undefined ? '' : profile.stakeholder_consultation_conducted ? '1' : '0', consultation_dates: profile?.consultation_dates?.length ? profile.consultation_dates : [''], completeness_checklist: { ...emptyChecklist, ...(profile?.completeness_checklist || {}) }, approval_status: profile?.approval_status || 'Draft', pamb_resolution_number: profile?.pamb_resolution_number || '', pamb_resolution_date: profile?.pamb_resolution_date || '', cenro_endorsement_date: profile?.cenro_endorsement_date || '', penro_endorsement_date: profile?.penro_endorsement_date || '', red_endorsement_date: profile?.red_endorsement_date || '', date_received_bmb: profile?.date_received_bmb || '', denr_affirmation_date: profile?.denr_affirmation_date || '', affirmation_reference: profile?.affirmation_reference || '', harmonized_adsdpp: profile?.harmonized_adsdpp || '', harmonized_clup: profile?.harmonized_clup || '', other_plans_integrated: profile?.other_plans_integrated || '', remarks: profile?.remarks || '', document_uploads: [], document_categories: [], removed_document_paths: [] });
  const documents = useProfileDocuments(profile?.documents || [], (files, categories, removed) => form.setData((data) => ({ ...data, document_uploads: files, document_categories: categories, removed_document_paths: removed })));
  const label = 'block text-xs font-semibold text-gray-700 dark:text-gray-300';
  const completed = Object.values(form.data.completeness_checklist).filter(Boolean).length;
  const submit = (event) => {event.preventDefault();form.transform((data) => ({ ...data, consultation_dates: (data.consultation_dates || []).filter(Boolean), ...(isEdit ? { _method: 'patch' } : {}) }));form.post(isEdit ? route('management-plans.types.profiles.update', [selectedPlanType.slug, profile.id]) : route('management-plans.types.profiles.store', selectedPlanType.slug), { forceFormData: true, preserveScroll: true, onSuccess: onClose });};
  const field = (name, text, props = {}) => <div className={label}><FloatingInput id={`plan-profile-${name}`} label={text} value={form.data[name]} onChange={(event) => form.setData(name, event.target.value)} {...props} />{form.errors[name] && <span className="mt-1 block text-xs text-red-500">{form.errors[name]}</span>}</div>;
  const select = (name, text, options) => <div className={label}><FloatingSelect id={`plan-profile-${name}`} label={text} value={form.data[name]} onChange={(event) => form.setData(name, event.target.value)}><option value="">Select</option>{options.map((option) => <option key={option} value={option}>{option === '1' ? 'Yes' : option === '0' ? 'No' : option}</option>)}</FloatingSelect>{form.errors[name] && <span className="mt-1 block text-xs text-red-500">{form.errors[name]}</span>}</div>;
  return <CrudFormModal open mode={isEdit ? 'edit' : 'create'} icon="📁" title={`${isEdit ? 'Edit' : 'Add'} ${selectedPlanType.name} Plan Information`} subtitle={`Management Plan: ${selectedPlanType.name}`} onClose={onClose} onSubmit={submit} processing={form.processing} errors={form.errors} saveLabel={isEdit ? 'Update Plan Information' : 'Add Plan Information'} preview={<ProfileDocuments manager={documents} categories={documentCategories} previewOnly />}>
        <div className="rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-xs text-green-800 dark:border-green-900 dark:bg-green-950/40 dark:text-green-300"><span className="font-semibold">Management Plan:</span> <span className="font-bold">{selectedPlanType.name}</span></div>
        <CrudSection title="Plan Information"><div className="grid gap-4 sm:grid-cols-2"><div className={label}><FloatingSelect id="planprofilefields-protected-area" label="Protected Area" value={form.data.protected_area_id} onChange={(event) => form.setData('protected_area_id', event.target.value)}><option value="">Select Protected Area</option>{protectedAreas.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</FloatingSelect>{form.errors.protected_area_id && <span className="mt-1 block text-xs text-red-500">{form.errors.protected_area_id}</span>}</div>{field('planning_period_start', 'Planning Period Start', { type: 'number', min: 1900, max: 2200 })}{field('planning_period_end', 'Planning Period End', { type: 'number', min: 1900, max: 2200 })}{field('lead_office', 'Lead Office / PAMO')}{field('lead_preparer', 'PASu / Lead Preparer')}</div></CrudSection>
        <CrudSection title="Plan Preparation"><div className="grid gap-4 sm:grid-cols-2">{field('date_preparation_started', 'Date Preparation Started', { type: 'date' })}{select('twg_constituted', 'Technical Working Group Constituted?', ['', '1', '0'].slice(1).map((value) => value))}<div className={label}><FloatingSelect id="planprofilefields-stakeholder-consultation-conducted" label="Stakeholder Consultation Conducted?" value={form.data.stakeholder_consultation_conducted} onChange={(event) => form.setData('stakeholder_consultation_conducted', event.target.value)}><option value="">Select</option><option value="1">Yes</option><option value="0">No</option></FloatingSelect></div><div className="sm:col-span-2"><p className={label}>Consultation Date/s</p><div className="mt-1.5 space-y-2">{form.data.consultation_dates.map((value, index) => <div key={index} className="flex gap-2"><FloatingInput id={`consultation-date-${index}`} label={`Consultation Date ${index + 1}`} type="date" value={value} onChange={(event) => {const next = [...form.data.consultation_dates];next[index] = event.target.value;form.setData('consultation_dates', next);}} /><button type="button" onClick={() => form.setData('consultation_dates', form.data.consultation_dates.filter((_, itemIndex) => itemIndex !== index))} className="rounded-xl border border-red-200 px-3 text-xs font-bold text-red-600 hover:bg-red-50">Remove</button></div>)}<button type="button" onClick={() => form.setData('consultation_dates', [...form.data.consultation_dates, ''])} className="rounded-xl border border-green-200 bg-green-50 px-3 py-2 text-xs font-bold text-green-700 hover:bg-green-100">+ Add Consultation Date</button></div></div></div></CrudSection>
        <CrudSection title="Plan Completeness" subtitle={`${completed} of 9 requirements completed`}><div className="grid gap-2 sm:grid-cols-2">{Object.entries(CHECKLIST).map(([key, text]) => <label key={key} className="flex items-start gap-2 rounded-xl border border-gray-200 p-3 text-xs font-semibold text-gray-700 dark:border-gray-700 dark:text-gray-200"><input type="checkbox" checked={Boolean(form.data.completeness_checklist[key])} onChange={(event) => form.setData('completeness_checklist', { ...form.data.completeness_checklist, [key]: event.target.checked })} className="mt-0.5 rounded border-gray-300 text-green-700 focus:ring-green-600" />{text}</label>)}</div></CrudSection>
        <CrudSection title="Plan Integration"><div className="grid gap-4 sm:grid-cols-3">{select('harmonized_adsdpp', 'Harmonized with ADSDPP?', ['Yes', 'No', 'Not Applicable'])}{select('harmonized_clup', 'Harmonized with CLUP?', ['Yes', 'No', 'Not Applicable'])}{select('other_plans_integrated', 'Other Relevant Plans Integrated?', ['Yes', 'No', 'Not Applicable'])}</div></CrudSection>
        <CrudSection title="Approval & Endorsement"><div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2">{select('approval_status', 'Approval Status', approvalStatuses)}{field('pamb_resolution_number', 'PAMB Resolution Number')}{field('pamb_resolution_date', 'PAMB Resolution Date', { type: 'date' })}{field('cenro_endorsement_date', 'CENRO Endorsement Date', { type: 'date' })}</div><div className="grid gap-4 sm:grid-cols-2">{field('penro_endorsement_date', 'PENRO Endorsement Date', { type: 'date' })}{field('red_endorsement_date', 'RED Endorsement Date', { type: 'date' })}{field('date_received_bmb', 'Date Received by BMB / Central Office', { type: 'date' })}{field('denr_affirmation_date', 'DENR Affirmation Date', { type: 'date' })}{field('affirmation_reference', 'Affirmation Reference / Document')}</div></div></CrudSection>
        <CrudSection title="Documents"><ProfileDocuments manager={documents} categories={documentCategories} error={form.errors.document_uploads || form.errors['document_uploads.0'] || form.errors.removed_document_paths} /></CrudSection>
        <CrudSection title="Remarks"><div className={label}><FloatingTextarea id="planprofilefields-remarks" label="Remarks" rows="4" value={form.data.remarks} onChange={(event) => form.setData('remarks', event.target.value)} /></div></CrudSection>
    </CrudFormModal>;
}

export function ProfileDetails({ profile }) {
  return <div className="space-y-6"><CrudSection title="Plan Information"><div className="grid gap-4 text-xs sm:grid-cols-2"><Detail label="Protected Area">{show(profile.protected_area_name)}</Detail><Detail label="Planning Period">{period(profile)}</Detail><Detail label="Lead Office / PAMO">{show(profile.lead_office)}</Detail><Detail label="PASu / Lead Preparer">{show(profile.lead_preparer)}</Detail></div></CrudSection><CrudSection title="Plan Preparation"><div className="grid gap-4 text-xs sm:grid-cols-2"><Detail label="Preparation Started">{formatReportDate(profile.date_preparation_started)}</Detail><Detail label="TWG Constituted">{yesNo(profile.twg_constituted)}</Detail><Detail label="Stakeholder Consultation Conducted">{yesNo(profile.stakeholder_consultation_conducted)}</Detail><Detail label="Consultation Dates">{profile.consultation_dates?.length ? profile.consultation_dates.map((date) => formatReportDate(date)).join(', ') : '—'}</Detail></div></CrudSection><CrudSection title="Plan Completeness"><p className="mb-3 text-xs font-bold text-green-700 dark:text-green-400">{completeness(profile)}</p><div className="grid gap-2 sm:grid-cols-2">{Object.entries(CHECKLIST).map(([key, text]) => <div key={key} className="flex items-center gap-2 text-xs text-gray-700 dark:text-gray-200"><span className={profile.completeness_checklist[key] ? 'text-green-600' : 'text-gray-400'}>{profile.completeness_checklist[key] ? '✓' : '○'}</span>{text}</div>)}</div></CrudSection><CrudSection title="Plan Integration"><div className="grid gap-4 text-xs sm:grid-cols-3"><Detail label="ADSDPP">{show(profile.harmonized_adsdpp)}</Detail><Detail label="CLUP">{show(profile.harmonized_clup)}</Detail><Detail label="Other Plans">{show(profile.other_plans_integrated)}</Detail></div></CrudSection><CrudSection title="Approval & Endorsement"><div className="grid gap-4 text-xs sm:grid-cols-2"><Detail label="Approval Status">{show(profile.approval_status)}</Detail><Detail label="PAMB Resolution Number">{show(profile.pamb_resolution_number)}</Detail><Detail label="PAMB Resolution Date">{formatReportDate(profile.pamb_resolution_date)}</Detail><Detail label="CENRO Endorsement">{formatReportDate(profile.cenro_endorsement_date)}</Detail><Detail label="PENRO Endorsement">{formatReportDate(profile.penro_endorsement_date)}</Detail><Detail label="RED Endorsement">{formatReportDate(profile.red_endorsement_date)}</Detail><Detail label="Received by BMB / Central Office">{formatReportDate(profile.date_received_bmb)}</Detail><Detail label="DENR Affirmation">{formatReportDate(profile.denr_affirmation_date)}</Detail><Detail label="Affirmation Reference">{show(profile.affirmation_reference)}</Detail></div></CrudSection><CrudSection title="Remarks"><p className="whitespace-pre-wrap text-xs text-gray-800 dark:text-gray-200">{profile.remarks || 'None.'}</p></CrudSection></div>;
}
