<?php

return [
    'enabled' => filter_var(env('COMPLIANCE_ALERTS_ENABLED', false), FILTER_VALIDATE_BOOL),
    'test_email_enabled' => filter_var(env('COMPLIANCE_TEST_EMAIL_ENABLED', false), FILTER_VALIDATE_BOOL),
    'send_time' => env('COMPLIANCE_ALERTS_SEND_TIME', '08:00'),
    'timezone' => 'Asia/Manila',
    'sender_display_name' => 'Enhanced Digital Alert and Tracking System (eDATS)',
    'to_label' => env('COMPLIANCE_ALERTS_TO_LABEL', 'Protected Area Management Office'),
    'attention_line' => env('COMPLIANCE_ALERTS_ATTENTION', 'Chief, Conservation and Development Section'),
    'from_line' => env('COMPLIANCE_ALERTS_FROM', 'The PENR Officer'),
    'email_subject' => '⚠ PRIORITY ACTION REQUIRED: Overdue Submission of PA-related Reports',
    'memorandum_subject' => env('COMPLIANCE_ALERTS_MEMORANDUM_SUBJECT', 'Submission of Reports of the Activities Already Conducted'),
    'introductory_text' => env('COMPLIANCE_ALERTS_INTRODUCTORY_TEXT', 'This is to respectfully remind your office that the deadline for the submission of the Protected Area Management-related report has already lapsed. We reiterate the importance of submitting your report to the PENRO as soon as possible.'),
    'compliance_warning_text' => env('COMPLIANCE_ALERTS_WARNING_TEXT', 'Please be advised that failure to comply may result in a rating of 1 (Poor) in the OPCR/IPCR. Thus, we highly encourage your immediate action to avoid any negative implications on our performance targets.'),
    'strict_compliance_text' => env('COMPLIANCE_ALERTS_STRICT_COMPLIANCE_TEXT', 'FOR INFORMATION AND STRICT COMPLIANCE, PLEASE.'),
    'signatory_name' => env('COMPLIANCE_ALERTS_SIGNATORY_NAME', 'PABLITO M. OFRECIA'),
    'signatory_position' => env('COMPLIANCE_ALERTS_SIGNATORY_POSITION', 'PENR Officer'),
    'office_name' => env('COMPLIANCE_ALERTS_OFFICE_NAME', 'PENRO Mati, Davao Oriental'),
    'office_address' => env('COMPLIANCE_ALERTS_OFFICE_ADDRESS', 'PENRO Mati, Davao Oriental'),
    'focal_person_name' => env('COMPLIANCE_ALERTS_FOCAL_PERSON_NAME', 'Richelle A. Benemerito'),
    'focal_person_position' => env('COMPLIANCE_ALERTS_FOCAL_PERSON_POSITION', 'EMS I'),
    'focal_person_contact' => env('COMPLIANCE_ALERTS_FOCAL_PERSON_CONTACT', 'Provincial Protected Area Focal Person of PENRO Mati'),
    'do_not_reply_text' => env('COMPLIANCE_ALERTS_DO_NOT_REPLY_TEXT', 'PLEASE DO NOT REPLY.'),
    'system_generated_footer_text' => env('COMPLIANCE_ALERTS_FOOTER_TEXT', 'This is a system-generated notification sent automatically by the Enhanced Digital Alert and Tracking System (eDATS). Notifications for a report will cease once the submission is recorded as compliant in eDATS.'),
    'fallback_recipient_email' => env('COMPLIANCE_ALERTS_RECIPIENTS', ''),
    'fallback_cc_emails' => env('COMPLIANCE_ALERTS_CC_RECIPIENTS', 'penromaticds@gmail.com,benemerito.RB@gmail.com,nely.maimad11@gmail.com,hingpitelmarie@gmail.com,duayelmarie@gmail.com,edhingpit01@gmail.com'),
    'approved_fallback_cc_emails' => array_values(array_filter(array_map('trim', explode(',', (string) env('COMPLIANCE_ALERTS_APPROVED_CC_RECIPIENTS', 'penromaticds@gmail.com,benemerito.RB@gmail.com,nely.maimad11@gmail.com,hingpitelmarie@gmail.com,duayelmarie@gmail.com,edhingpit01@gmail.com'))))),
    'test_recipient_email' => env('COMPLIANCE_ALERTS_TEST_RECIPIENT_EMAIL', ''),
    // Backward-compatible aliases for Phase 1 integrations.
    'sender_name' => 'Enhanced Digital Alert and Tracking System (eDATS)',
    'attention' => env('COMPLIANCE_ALERTS_ATTENTION', 'Chief, Conservation and Development Section'),
    'from' => env('COMPLIANCE_ALERTS_FROM', 'The PENR Officer'),
    'subject' => '⚠ PRIORITY ACTION REQUIRED: Overdue Submission of PA-related Reports',
    'recipients' => array_values(array_filter(array_map('trim', explode(',', (string) env('COMPLIANCE_ALERTS_RECIPIENTS', ''))))),
    'cc_recipients' => array_values(array_filter(array_map('trim', explode(',', (string) env('COMPLIANCE_ALERTS_CC_RECIPIENTS', ''))))),
];
