<?php

return [
    'enabled' => filter_var(env('COMPLIANCE_ALERTS_ENABLED', false), FILTER_VALIDATE_BOOL),
    'test_email_enabled' => filter_var(env('COMPLIANCE_TEST_EMAIL_ENABLED', false), FILTER_VALIDATE_BOOL),
    'send_time' => env('COMPLIANCE_ALERTS_SEND_TIME', '08:00'),
    'timezone' => 'Asia/Manila',
    'sender_display_name' => env('COMPLIANCE_ALERTS_SENDER_NAME', 'CDS Information Management System'),
    'to_label' => env('COMPLIANCE_ALERTS_TO_LABEL', 'Protected Area Management Office'),
    'attention_line' => env('COMPLIANCE_ALERTS_ATTENTION', 'The Protected Area Superintendent / Concerned Officer'),
    'from_line' => env('COMPLIANCE_ALERTS_FROM', 'The PENR Officer'),
    'email_subject' => env('COMPLIANCE_ALERTS_SUBJECT', 'PRIORITY ACTION REQUIRED: Overdue Submission of PA-related Reports'),
    'memorandum_subject' => env('COMPLIANCE_ALERTS_MEMORANDUM_SUBJECT', 'Submission of Reports of the Activities Already Conducted'),
    'introductory_text' => env('COMPLIANCE_ALERTS_INTRODUCTORY_TEXT', 'The required PA Management-related report deadline has already lapsed. Kindly submit the required report(s) to PENRO as soon as possible.'),
    'compliance_warning_text' => env('COMPLIANCE_ALERTS_WARNING_TEXT', 'Failure to comply may result in a rating of 1 (Poor) in OPCR/IPCR. Immediate action is encouraged to avoid negative implications on collective performance targets.'),
    'strict_compliance_text' => env('COMPLIANCE_ALERTS_STRICT_COMPLIANCE_TEXT', 'FOR INFORMATION AND STRICT COMPLIANCE, PLEASE.'),
    'signatory_name' => env('COMPLIANCE_ALERTS_SIGNATORY_NAME', 'PABLITO M. OFRECIA'),
    'signatory_position' => env('COMPLIANCE_ALERTS_SIGNATORY_POSITION', 'PENR Officer'),
    'office_name' => env('COMPLIANCE_ALERTS_OFFICE_NAME', 'PENRO Mati, Davao Oriental'),
    'office_address' => env('COMPLIANCE_ALERTS_OFFICE_ADDRESS', 'PENRO Mati, Davao Oriental'),
    'focal_person_name' => env('COMPLIANCE_ALERTS_FOCAL_PERSON_NAME', 'Richelle A. Benemerito'),
    'focal_person_position' => env('COMPLIANCE_ALERTS_FOCAL_PERSON_POSITION', 'EMS I'),
    'focal_person_contact' => env('COMPLIANCE_ALERTS_FOCAL_PERSON_CONTACT', 'Provincial Protected Area Focal Person of PENRO Mati'),
    'do_not_reply_text' => env('COMPLIANCE_ALERTS_DO_NOT_REPLY_TEXT', 'PLEASE DO NOT REPLY.'),
    'system_generated_footer_text' => env('COMPLIANCE_ALERTS_FOOTER_TEXT', 'This automated reminder concerns reports whose authoritative submission or receipt has not yet been recorded by PENRO. Reminders cease once the report is recorded as received or submitted by PENRO. Records verification is a separate internal audit process.'),
    'fallback_recipient_email' => env('COMPLIANCE_ALERTS_RECIPIENTS', ''),
    'fallback_cc_emails' => env('COMPLIANCE_ALERTS_CC_RECIPIENTS', 'penromaticds@gmail.com,benemerito.RB@gmail.com,nely.maimad11@gmail.com,hingpitelmarie@gmail.com,duayelmarie@gmail.com,edhingpit01@gmail.com'),
    'approved_fallback_cc_emails' => array_values(array_filter(array_map('trim', explode(',', (string) env('COMPLIANCE_ALERTS_APPROVED_CC_RECIPIENTS', 'penromaticds@gmail.com,benemerito.RB@gmail.com,nely.maimad11@gmail.com,hingpitelmarie@gmail.com,duayelmarie@gmail.com,edhingpit01@gmail.com'))))),
    'test_recipient_email' => env('COMPLIANCE_ALERTS_TEST_RECIPIENT_EMAIL', ''),
    // Backward-compatible aliases for Phase 1 integrations.
    'sender_name' => env('COMPLIANCE_ALERTS_SENDER_NAME', 'CDS Information Management System'),
    'attention' => env('COMPLIANCE_ALERTS_ATTENTION', 'The Protected Area Superintendent / Concerned Officer'),
    'from' => env('COMPLIANCE_ALERTS_FROM', 'The PENR Officer'),
    'subject' => env('COMPLIANCE_ALERTS_SUBJECT', 'PRIORITY ACTION REQUIRED: Overdue Submission of PA-related Reports'),
    'recipients' => array_values(array_filter(array_map('trim', explode(',', (string) env('COMPLIANCE_ALERTS_RECIPIENTS', ''))))),
    'cc_recipients' => array_values(array_filter(array_map('trim', explode(',', (string) env('COMPLIANCE_ALERTS_CC_RECIPIENTS', ''))))),
];
