import React, { useEffect, useMemo, useState } from 'react';
import { MapContainer, TileLayer, Marker, Popup, LayersControl, LayerGroup, GeoJSON, useMap } from 'react-leaflet';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import SpatialLayerPanel from '@/Components/SpatialLayerPanel';

function FitLayers({ layers }) { const map = useMap(); const signature = layers.map(layer => layer.id).join(','); useEffect(() => { const bounds = L.featureGroup(layers.map(layer => L.geoJSON(layer.geojson))).getBounds(); if (bounds.isValid()) map.fitBounds(bounds, { padding: [50, 50] }); }, [signature, map]); return null; }

export default function MapView({ bamsRecords = [], spatialLayers = [], floraIcon, faunaIcon, canManageSpatial = false, onAddSpatialLayer = () => {} }) {
    const layers = useMemo(() => (Array.isArray(spatialLayers) ? spatialLayers : []), [spatialLayers]);
    const [visibleLayers, setVisibleLayers] = useState(() => Object.fromEntries(layers.map(layer => [layer.id, true])));
    useEffect(() => setVisibleLayers(current => Object.fromEntries(layers.map(layer => [layer.id, current[layer.id] !== false]))), [layers]);
    return <div className="mx-auto w-full max-w-7xl space-y-4 overflow-hidden rounded-2xl border border-gray-100 bg-white p-6 shadow-xl dark:border-gray-700 dark:bg-gray-800"><div><h3 className="text-xl font-extrabold text-gray-900 dark:text-white">BAMS Geographic Distribution Map</h3><p className="mt-0.5 text-xs text-gray-500 dark:text-gray-400">PMP observations and independently managed spatial layers.</p></div><div className="relative h-[720px] w-full overflow-hidden rounded-2xl border border-gray-200 shadow-inner dark:border-gray-700"><MapContainer center={[6.9573, 126.1979]} zoom={11} scrollWheelZoom style={{ height: '100%', width: '100%' }}><LayersControl position="topright"><LayersControl.BaseLayer checked name="Standard (OpenStreetMap)"><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" /></LayersControl.BaseLayer><LayersControl.BaseLayer name="Satellite Imagery"><TileLayer attribution="Tiles &copy; Esri" url="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}" /></LayersControl.BaseLayer><LayersControl.BaseLayer name="Hybrid"><LayerGroup><TileLayer url="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}" /><TileLayer url="https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}" /></LayerGroup></LayersControl.BaseLayer></LayersControl>{layers.filter(layer => visibleLayers[layer.id] !== false).map(layer => <GeoJSON key={`spatial-${layer.id}`} data={layer.geojson} style={{ color: '#047857', weight: 3, fillColor: '#10b981', fillOpacity: 0.3 }} />)}<FitLayers layers={layers} />{canManageSpatial && <SpatialLayerPanel layers={layers} visibleLayers={visibleLayers} onToggle={id => setVisibleLayers(current => ({ ...current, [id]: current[id] === false }))} deleteRoute="bams.spatial-layers.destroy" onAdd={onAddSpatialLayer} />}{(Array.isArray(bamsRecords) ? bamsRecords : []).filter(record => record?.latitude && record?.longitude).map(record => <Marker key={`bams-${record.id}`} position={[parseFloat(record.latitude), parseFloat(record.longitude)]} icon={record.category === 'Fauna' ? faunaIcon : floraIcon}><Popup><strong>{record.species_code || record.species_name}</strong><br />Plot / Quadrat: {record.plot_no || 'N/A'} / {record.quadrat_no || 'N/A'}</Popup></Marker>)}</MapContainer></div></div>;
}
