import { FloatingInput, FloatingSelect, FloatingTextarea } from '@/Components/Form';
import { router, useForm, usePage } from '@inertiajs/react';
import { useState } from 'react';
import CrudDetailsModal from '@/Components/Crud/CrudDetailsModal';
import CrudFormModal from '@/Components/Crud/CrudFormModal';
import CrudSection from '@/Components/Crud/CrudSection';
import CrudSummaryGrid from '@/Components/Crud/CrudSummaryGrid';
import CrudTable from '@/Components/Crud/CrudTable';
import ConfirmDialog from '@/Components/ConfirmDialog';
import { formatReportDate } from '@/Utils/dateFormatters';
import { formatMoney } from '@/Utils/moneyFormatters';
import Tooltip from '@/Components/Tooltip';

const labelClass = 'block text-xs font-semibold text-gray-700 dark:text-gray-300';
const peso = (value) => value === null || value === undefined ? '—' : `₱${formatMoney(value)}`;
const show = (value) => value === null || value === undefined || value === '' ? '—' : value;
const updatedAt = (value) => value ? new Intl.DateTimeFormat('en-PH', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—';
const areaName = (row) => <span className={row.is_total ? 'font-extrabold text-green-900 dark:text-green-300' : 'font-semibold'}>{row.protected_area_name}</span>;
const Detail = ({ label, value }) => <div><p className="text-[11px] font-semibold uppercase tracking-wide text-gray-500 dark:text-gray-400">{label}</p><p className="mt-1 text-sm font-semibold text-gray-900 dark:text-white">{value}</p></div>;

export default function AccountingSection({ accounting = {}, protectedAreas = [], filters = {} }) {
  const { auth = {}, errors = {} } = usePage().props;
  const canUpdate = Boolean(auth.canUpdateTechnicalReports);
  const [formMode, setFormMode] = useState(null); const [selected, setSelected] = useState(null); const [editingSynced, setEditingSynced] = useState(false); const [syncing, setSyncing] = useState(false); const [confirmingSync, setConfirmingSync] = useState(false);
  const form = useForm({ protected_area_id: '', reporting_year: accounting.year || new Date().getFullYear(), accounting_protected_area_id: filters.accounting_protected_area_id || '', total_ipaf_collection: '', bank_balance: '', status_note: '' });
  const apply = (changes) => router.get(route('ipaf.index'), { ...filters, ipaf_tab: 'accounting', ...changes }, { preserveState: true, preserveScroll: true, replace: true });
  const openAdd = () => { form.clearErrors(); setEditingSynced(false); form.setData({ protected_area_id: '', reporting_year: accounting.year || new Date().getFullYear(), accounting_protected_area_id: filters.accounting_protected_area_id || '', total_ipaf_collection: '', bank_balance: '', status_note: '' }); setFormMode('add'); };
  const openEdit = (record) => { form.clearErrors(); setEditingSynced(record.accounting_data_source === 'Google Sheets' && record.bank_balance_sync_status === 'synced'); form.setData({ protected_area_id: String(record.protected_area_id), reporting_year: record.reporting_year, accounting_protected_area_id: filters.accounting_protected_area_id || '', total_ipaf_collection: record.total_ipaf_collection, bank_balance: record.bank_balance, status_note: record.status_note ?? '' }); setSelected(null); setFormMode('edit'); };
  const closeForm = () => { setFormMode(null); setEditingSynced(false); form.reset(); form.clearErrors(); };
  const submit = (event) => { event.preventDefault(); form.put(route('ipaf.accounting-status.update'), { preserveScroll: true, onSuccess: closeForm }); };
  const syncAccounting = () => { if (syncing) return; router.post(route('ipaf.accounting.bank-balances.sync'), { reporting_year: Number(accounting.year), accounting_protected_area_id: filters.accounting_protected_area_id || null }, { preserveScroll: true, onStart: () => setSyncing(true), onSuccess: () => setConfirmingSync(false), onError: () => setConfirmingSync(false), onFinish: () => setSyncing(false) }); };
  const savedRows = accounting.rows || []; const provincialTotals = accounting.provincial_totals || {};
  const rows = [...savedRows, { id: 'accounting-total', protected_area_id: 'accounting-total', protected_area_name: 'PENRO DAVAO ORIENTAL TOTAL', total_ipaf_collection: provincialTotals.total_ipaf_collection, bank_balance: provincialTotals.bank_balance, status_note: '', is_total: true }];
  const columns = [
    { key: 'protected_area_name', label: 'Name of PA', headerClassName: 'w-[30%] !whitespace-normal', cellClassName: 'whitespace-normal break-words', render: areaName },
    { key: 'total_ipaf_collection', label: <span>Total IPAF Collection<br /><span className="normal-case tracking-normal">(From previous years to present)</span></span>, headerClassName: 'w-[25%] !whitespace-normal text-right', cellClassName: 'text-right tabular-nums', render: (row) => <span className={row.is_total ? 'font-extrabold' : ''}>{peso(row.total_ipaf_collection)}</span> },
    { key: 'bank_balance', label: 'Bank Balance', headerClassName: 'w-[20%] !whitespace-normal text-right', cellClassName: 'text-right tabular-nums', render: (row) => <span className={row.is_total ? 'font-extrabold' : ''}>{peso(row.bank_balance)}</span> },
    { key: 'status_note', label: 'Status / Note', headerClassName: 'w-[25%] !whitespace-normal', cellClassName: 'whitespace-normal break-words', render: (row) => show(row.status_note) },
  ];
  const filtersUi = <div className="grid gap-3 sm:grid-cols-2 lg:max-w-2xl"><FloatingSelect id="accounting-year" label="Reporting Year" size="sm" value={accounting.year || ''} onChange={(event) => apply({ accounting_year: event.target.value })}>{(accounting.years || []).map((year) => <option key={year} value={year}>{year}</option>)}</FloatingSelect><FloatingSelect id="accounting-pa" label="Protected Area" size="sm" value={filters.accounting_protected_area_id || ''} onChange={(event) => apply({ accounting_protected_area_id: event.target.value })}><option value="">All Protected Areas</option>{protectedAreas.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</FloatingSelect></div>;
  return <section className="mt-5 space-y-4">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-green-700 dark:text-green-400">Accounting Section</p><h2 className="mt-1 text-xl font-extrabold uppercase text-gray-900 dark:text-white">STATUS OF IPAF BASED FROM ACCOUNTING SECTION</h2><p className="mt-1 text-xs text-gray-500 dark:text-gray-400">Official Accounting Section cumulative collection and bank-balance records.</p></div>{canUpdate && <div className="flex flex-wrap gap-2"><Tooltip content="Synchronize official Accounting collection and bank-balance values."><button type="button" disabled={syncing} onClick={() => setConfirmingSync(true)} className="rounded-xl border border-green-700 bg-white px-4 py-2.5 text-xs font-bold text-green-800 shadow-sm transition hover:bg-green-50 focus:outline-none focus-visible:ring-2 focus-visible:ring-green-600 disabled:cursor-not-allowed disabled:opacity-50 dark:bg-gray-900 dark:text-green-300 dark:hover:bg-green-950/30">{syncing ? 'Synchronizing…' : 'Sync Accounting Data'}</button></Tooltip><button type="button" onClick={openAdd} className="rounded-xl bg-green-700 px-4 py-2.5 text-xs font-bold text-white shadow-sm transition hover:bg-green-800 focus:outline-none focus-visible:ring-2 focus-visible:ring-green-600">+ Add Accounting Data</button></div>}</div>
    <p className="text-xs text-gray-500 dark:text-gray-400">The source snapshot date and reporting year are read from the official Google Sheet heading when synchronization starts. A mismatched reporting year is blocked.</p>
    {errors.bank_balance_sync && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700 dark:border-red-900 dark:bg-red-950/30 dark:text-red-300">{errors.bank_balance_sync}</div>}
    <div className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-900">{filtersUi}</div>
    <CrudSummaryGrid items={[{ label: 'Official Total IPAF Collection', value: peso(accounting.totals?.total_ipaf_collection) }, { label: 'Official Total Bank Balance', value: peso(accounting.totals?.bank_balance) }]} columns={2} />
    {savedRows.length === 0 && <div className="rounded-xl border border-dashed border-gray-300 bg-gray-50 px-4 py-3 text-sm text-gray-600 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-400">No accounting data recorded for this reporting year.</div>}
    <CrudTable title="Accounting Records" subtitle={`Reporting Year ${accounting.year}`} helperText={savedRows.length ? 'Click any accounting record to view full details' : undefined} columns={columns} rows={rows} rowKey="id" onRowClick={setSelected} isRowDisabled={(row) => row.is_total} emptyTitle="No accounting data recorded for this reporting year." emptyDescription="Add official Accounting Section values when they become available." tableClassName="w-full min-w-[760px] table-fixed" />
    <CrudDetailsModal open={Boolean(selected)} title="Accounting Details" subtitle={selected ? `${selected.protected_area_name} · Reporting Year ${selected.reporting_year}` : ''} onClose={() => setSelected(null)} canEdit={canUpdate} onEdit={() => openEdit(selected)} editLabel="Edit Accounting Data" summary={selected && <CrudSummaryGrid items={[{ label: 'Protected Area', value: selected.protected_area_name }, { label: 'Reporting Year', value: selected.reporting_year }, { label: 'Total IPAF Collection', value: peso(selected.total_ipaf_collection) }, { label: 'Bank Balance', value: peso(selected.bank_balance) }]} />}>
      {selected && <CrudSection title="Accounting Record"><div className="grid gap-4 sm:grid-cols-2"><Detail label="Total IPAF Collection (From previous years to present)" value={peso(selected.total_ipaf_collection)} /><Detail label="Bank Balance" value={peso(selected.bank_balance)} /><Detail label="Status / Note" value={show(selected.status_note)} /><Detail label="Last Updated" value={updatedAt(selected.updated_at)} /><Detail label="Accounting Data Source" value={show(selected.accounting_data_source)} /><Detail label="Source As Of" value={formatReportDate(selected.bank_balance_source_as_of)} /><Detail label="Total IPAF Collection Source" value={show(selected.total_ipaf_collection_source_reference)} /><Detail label="Bank Balance Source" value={show(selected.bank_balance_source_reference)} /><Detail label="Last Synced" value={updatedAt(selected.bank_balance_synced_at)} /><Detail label="Sync Status" value={selected.bank_balance_sync_status === 'synced' ? 'Synced' : show(selected.bank_balance_sync_status)} /></div></CrudSection>}
    </CrudDetailsModal>
    <CrudFormModal open={Boolean(formMode)} mode={formMode === 'edit' ? 'edit' : 'create'} title={formMode === 'edit' ? 'Edit Accounting Data' : 'Add Accounting Data'} subtitle="Official manual values from the Accounting Section" onClose={closeForm} onSubmit={submit} processing={form.processing} errors={form.errors} saveLabel={formMode === 'edit' ? 'Update Accounting Data' : 'Add Accounting Data'} maxWidth="max-w-3xl">
      <CrudSection title="Accounting Information"><div className="grid gap-4 sm:grid-cols-2"><div className={labelClass}><FloatingSelect id="accountingsection-protected-area" label="Protected Area" required disabled={formMode === 'edit'} value={form.data.protected_area_id} onChange={(event) => form.setData('protected_area_id', event.target.value)}><option value="">Select Protected Area</option>{protectedAreas.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</FloatingSelect>{form.errors.protected_area_id && <span className="mt-1 block text-xs text-red-500">{form.errors.protected_area_id}</span>}</div><div className={labelClass}><FloatingSelect id="accountingsection-reporting-year" label="Reporting Year" required disabled={formMode === 'edit'} value={String(form.data.reporting_year || '')} onChange={(event) => form.setData('reporting_year', event.target.value)} size="sm">{(accounting.years || []).map((year) => <option key={year} value={year}>{year}</option>)}</FloatingSelect>{form.errors.reporting_year && <span className="mt-1 block text-xs text-red-500">{form.errors.reporting_year}</span>}</div></div></CrudSection>
      <CrudSection title="Accounting Values"><div className="grid gap-4 sm:grid-cols-2"><div className={labelClass}><FloatingInput id="accountingsection-total-ipaf-collection-from-previous-years-to-present" label="Total IPAF Collection (From previous years to present)" required readOnly={editingSynced} type="number" min="0" step="0.01" value={form.data.total_ipaf_collection} onChange={(event) => form.setData('total_ipaf_collection', event.target.value)} /><span className="mt-1 block text-[11px] font-normal leading-4 text-gray-500">{editingSynced ? 'Automatically synchronized from the official IPAF Accounting Google Sheet.' : 'Official cumulative IPAF collection reported by the Accounting Section. This is independent from Revenue Collection monitoring totals.'}</span>{form.errors.total_ipaf_collection && <span className="mt-1 block text-xs text-red-500">{form.errors.total_ipaf_collection}</span>}</div><div className={labelClass}><FloatingInput id="accountingsection-bank-balance" label="Bank Balance" required readOnly={editingSynced} type="number" min="0" step="0.01" value={form.data.bank_balance} onChange={(event) => form.setData('bank_balance', event.target.value)} /><span className="mt-1 block text-[11px] font-normal leading-4 text-gray-500">{editingSynced ? 'Automatically synchronized from the official IPAF Accounting Google Sheet.' : 'Official bank balance reported by the Accounting Section.'}</span>{form.errors.bank_balance && <span className="mt-1 block text-xs text-red-500">{form.errors.bank_balance}</span>}</div></div><div className={`${labelClass} mt-4`}><FloatingTextarea id="accountingsection-status-note" label="Status / Note" rows="4" value={form.data.status_note} onChange={(event) => form.setData('status_note', event.target.value)} />{form.errors.status_note && <span className="mt-1 block text-xs text-red-500">{form.errors.status_note}</span>}</div></CrudSection>
    </CrudFormModal>
    <ConfirmDialog open={confirmingSync} title="Synchronize Accounting Data?" message="Synchronize Total IPAF Collection and Bank Balance from the official IPAF Accounting Google Sheet? Existing synchronized values for the matching source year will be updated." confirmLabel="Synchronize" processing={syncing} onCancel={() => !syncing && setConfirmingSync(false)} onConfirm={syncAccounting} />
  </section>;
}
