import { FloatingInput, FloatingSelect, FloatingTextarea } from "@/Components/Form";import { router, useForm, usePage } from '@inertiajs/react';
import { useEffect, useState } from 'react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import ConfirmDialog from '@/Components/ConfirmDialog';
import CrudDetailsModal from '@/Components/Crud/CrudDetailsModal';
import CrudFormModal from '@/Components/Crud/CrudFormModal';
import CrudSection from '@/Components/Crud/CrudSection';
import CrudSummaryGrid from '@/Components/Crud/CrudSummaryGrid';
import CrudTable from '@/Components/Crud/CrudTable';
import FileAttachmentPanel from '@/Components/Crud/FileAttachmentPanel';
import FilePreviewPanel from '@/Components/Crud/FilePreviewPanel';
import { useReportDetails } from '@/Components/Crud/ReportDetailsContext';
import PageHeader from '@/Components/PageHeader';
import { formatReportDate } from '@/Utils/dateFormatters';
import { formatMoney } from '@/Utils/moneyFormatters';
import TimelinessBadge, { isTimelinessValue } from '@/Components/TimelinessBadge';
import AccountingSection from './AccountingSection';
import IpafAnalysis from './IpafAnalysis';
import RevenueQuarterlySummary from './RevenueQuarterlySummary';

const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
const label = 'block text-xs font-semibold text-gray-700 dark:text-gray-300';
const tabClass = (active) => `inline-flex shrink-0 items-center rounded-xl border px-4 py-2.5 text-xs font-bold transition focus:outline-none focus-visible:ring-2 focus-visible:ring-green-600 ${active ? 'border-green-700 bg-green-700 text-white shadow-md' : 'border-gray-200 bg-white text-gray-700 shadow-sm hover:border-green-300 hover:bg-green-50 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-300'}`;
const show = (value) => value === null || value === undefined || value === '' ? '\u2014' : value;
const money = (value) => value === null || value === undefined ? '\u2014' : `\u20B1${formatMoney(value)}`;
const badgeClass = (value) => ({ 'Report Submitted': 'bg-green-600 text-white', 'Completed': 'bg-green-600 text-white', 'Report Not Yet Submitted': 'bg-red-600 text-white', 'Ongoing Preparation at CENRO Level': 'bg-blue-600 text-white', 'Pending Submission by CENRO': 'bg-blue-600 text-white', 'Pending Receipt by PENRO': 'bg-blue-600 text-white', 'Pending Regional Endorsement': 'bg-blue-600 text-white' })[value] || 'bg-gray-500 text-white';
const Badge = ({ value }) => isTimelinessValue(value) ? <TimelinessBadge value={value} /> : <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${badgeClass(value)}`}>{show(value)}</span>;
const Detail = ({ label: heading, children }) => {
  const reportDetails = useReportDetails();
  const inSummary = /^(reporting period|semester|quarter|deadline|timeliness|submission status|status|report status|number of days complied|days complied)$/i.test(heading);
  if (reportDetails && inSummary) return null;
  return <div><span className="block text-xs text-gray-500">{heading}</span><span className="font-semibold text-gray-800 dark:text-gray-200">{children}</span></div>;
};

export default function Index(props) {
  const management = props.filters?.ipaf_tab === 'management';
  if (management) {
    return <AuthenticatedLayout title="Management of IPAF"><PageHeader title="Management of IPAF" description="IPAF report submission and timeliness monitoring." /><Tracker kind="management" rows={props.managementReports} protectedAreas={props.protectedAreas} filters={props.filters} /></AuthenticatedLayout>;
  }
  const tabs = [{ key: 'revenue', label: 'Revenue Collection' }, { key: 'quarterly', label: 'Quarterly Performance' }, { key: 'accounting', label: 'Accounting Section' }, { key: 'analysis', label: 'IPAF Analysis' }];
  const activeTab = tabs.some((tab) => tab.key === props.filters?.ipaf_tab) ? props.filters.ipaf_tab : 'revenue';
  const setActiveTab = (tab) => router.get(route('ipaf.index'), { ...props.filters, ipaf_tab: tab }, { preserveState: true, preserveScroll: true, replace: true });
  return <AuthenticatedLayout title="Revenue Collection"><PageHeader title="Revenue Collection" description="Integrated Protected Area Fund revenue monitoring and financial performance" /><div className="mt-3 flex gap-1.5 overflow-x-auto pb-1" role="tablist" aria-label="IPAF revenue and financial views">{tabs.map((tab) => <button key={tab.key} type="button" role="tab" aria-selected={activeTab === tab.key} className={tabClass(activeTab === tab.key)} onClick={() => setActiveTab(tab.key)}>{tab.label}</button>)}</div>{activeTab === 'revenue' && <Tracker kind="revenue" rows={props.revenueCollections} totals={props.revenueTotals} protectedAreas={props.protectedAreas} filters={props.filters} />} {activeTab === 'quarterly' && <RevenueQuarterlySummary summary={props.quarterlyRevenueSummary} targets={props.revenueTargets} annual={props.annualRevenuePerformance} protectedAreas={props.protectedAreas} filters={props.filters} />} {activeTab === 'accounting' && <AccountingSection accounting={props.accountingStatusSummary} protectedAreas={props.protectedAreas} filters={props.filters} />} {activeTab === 'analysis' && <IpafAnalysis analysis={props.ipafAnalysis} protectedAreas={props.protectedAreas} filters={props.filters} />}</AuthenticatedLayout>;
}

function Tracker({ kind, rows = {}, totals, protectedAreas = [], filters = {} }) {
  const revenue = kind === 'revenue';const { auth = {} } = usePage().props;const canCreate = Boolean(auth.canCreateTechnicalReports),canUpdate = Boolean(auth.canUpdateTechnicalReports),canDelete = Boolean(auth.canDeleteTechnicalReports);
  const records = rows.data || [];const [selected, setSelected] = useState(null),[modal, setModal] = useState(null),[deleting, setDeleting] = useState(null),[preview, setPreview] = useState(null);
  const empty = revenue ? { protected_area_id: '', target_office: '', document_type: '', reporting_month: new Date().getMonth() + 1, reporting_year: new Date().getFullYear(), total_collected: '', deadline_submission: '', mov: null, remarks: '' } : { protected_area_id: '', target_office: '', document_type: '', date_conducted: '', date_accomplished: '', mov: null, remarks: '' };
  const form = useForm(empty);
  useEffect(() => () => {if (preview?.temporary) URL.revokeObjectURL(preview.url);}, [preview]);
  useEffect(() => {if (!selected) return;const fresh = records.find((row) => row.id === selected.id);if (fresh) setSelected(fresh);}, [rows.data]);
  const openCreate = () => {form.setData(empty);form.clearErrors();setSelected(null);setPreview(null);setModal('create');};
  const openEdit = (record) => {setSelected(record);form.clearErrors();form.setData({ ...empty, ...record, mov: null });setPreview(record.mov);setModal('edit');};
  const close = () => {setModal(null);setSelected(null);setPreview(null);form.reset();form.clearErrors();};
  const selectMov = (file) => {form.setData((data) => ({ ...data, mov: file }));setPreview(file ? { name: file.name, type: file.type, size: file.size, url: URL.createObjectURL(file), temporary: true } : selected?.mov || null);};
  const prefix = revenue ? 'ipaf.revenue' : 'ipaf.management';
  const submit = (e) => {e.preventDefault();const edit = modal === 'edit';form.transform((data) => edit ? { ...data, _method: 'put' } : data);const endpoint = edit ? route(`${prefix}.update`, selected.id) : route(`${prefix}.store`);form.post(endpoint, { forceFormData: true, preserveScroll: true, onSuccess: close });};
  const apply = (changes) => router.get(route('ipaf.index'), { ...filters, revenue_search: undefined, management_search: undefined, ...changes }, { preserveState: true, preserveScroll: true, replace: true });
  const columns = revenue ? [
  { key: 'protected_area_name', label: 'Name of PA', render: (r) => <b>{show(r.protected_area_name)}</b> }, { key: 'reporting_month', label: 'Month', render: (r) => `${months[r.reporting_month - 1]} ${r.reporting_year}` }, { key: 'total_collected', label: 'Total Collected', render: (r) => money(r.total_collected) }, { key: 'ipaf_ria', label: 'IPAF RIA (75%)', render: (r) => money(r.ipaf_ria) }, { key: 'sagf', label: 'SAGF (25%)', render: (r) => money(r.sagf) }, { key: 'date_received_penro', label: 'Received by PENRO', render: (r) => formatReportDate(r.date_received_penro) }, { key: 'timeliness', label: 'Timeliness', render: (r) => <Badge value={r.timeliness} /> }, { key: 'submission_status', label: 'Status of Submission', render: (r) => <Badge value={r.submission_status} /> }] :
  [{ key: 'protected_area_name', label: 'Name of PA', render: (r) => <b>{show(r.protected_area_name)}</b> }, { key: 'activity_name', label: 'Name of Activity', render: (r) => show(r.activity_name) }, { key: 'date_conducted', label: 'Date Conducted', render: (r) => show(r.date_conducted) }, { key: 'document_type', label: 'Type of Document', render: (r) => show(r.document_type) }, { key: 'date_accomplished', label: 'Date Accomplished', render: (r) => formatReportDate(r.date_accomplished) }, { key: 'timeliness', label: 'Timeliness', render: (r) => <Badge value={r.timeliness} /> }, { key: 'submission_status', label: 'Status of Submission', render: (r) => <Badge value={r.submission_status} /> }];
  const filterUi = <div className="grid gap-3 sm:grid-cols-2">{revenue && <div className={label}><FloatingInput id="index-reporting-period" label="Reporting Period" type="month" value={filters.revenue_year && filters.revenue_month ? `${filters.revenue_year}-${String(filters.revenue_month).padStart(2, '0')}` : ''} onChange={(e) => { const [year, month] = e.target.value.split('-'); apply({ revenue_year: year || undefined, revenue_month: month || undefined, revenue_page: 1 }); }} /></div>}<div className={label}><FloatingSelect id="index-protected-area" label="Protected Area" value={filters[`${kind}_protected_area_id`] || ''} onChange={(e) => apply({ [`${kind}_protected_area_id`]: e.target.value || undefined, [`${kind}_page`]: 1 })}><option value="">All</option>{protectedAreas.map((pa) => <option key={pa.id} value={pa.id}>{pa.name}</option>)}</FloatingSelect></div></div>;
  const pagination = rows.links?.length > 3 ? <div className="flex flex-wrap gap-1">{rows.links.map((link, i) => <button key={i} disabled={!link.url || link.active} onClick={() => link.url && router.get(link.url, {}, { preserveState: true, preserveScroll: true })} className={`rounded-lg px-3 py-1.5 text-xs font-bold ${link.active ? 'bg-green-700 text-white' : 'bg-gray-100 dark:bg-gray-700 dark:text-white'} disabled:opacity-50`} dangerouslySetInnerHTML={{ __html: link.label }} />)}</div> : null;
  return <div className="mt-5 space-y-4"><div className="rounded-2xl border border-gray-100 bg-white p-4 shadow-xl dark:border-gray-800 dark:bg-gray-900"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div className="min-w-0 flex-1">{filterUi}</div>{canCreate && <button type="button" onClick={openCreate} className="shrink-0 rounded-xl bg-green-700 px-4 py-2.5 text-xs font-bold text-white shadow-sm transition hover:bg-green-800 focus:outline-none focus-visible:ring-2 focus-visible:ring-green-600">+ {revenue ? 'Add Revenue Collection' : 'Add Report'}</button>}</div></div>{revenue && <CrudSummaryGrid items={[{ label: 'Total Collected', value: money(totals?.total_collected) }, { label: 'IPAF RIA 75%', value: money(totals?.ipaf_ria) }, { label: 'SAGF 25%', value: money(totals?.sagf) }]} />}<CrudTable compactEmpty={true} title={records.length > 0 ? (revenue ? 'Revenue Collection' : 'Management of IPAF') : undefined} subtitle={records.length > 0 ? `${rows.total ?? records.length} records` : undefined} helperText={records.length > 0 ? 'Click any row to view full details' : undefined} columns={columns} rows={records} rowKey="id" onRowClick={(record) => {setSelected(record);setModal('details');}} pagination={records.length > 0 ? pagination : null} emptyTitle="No records found" emptyDescription="No IPAF records match the selected filters." />
        <CrudDetailsModal open={modal === 'details' && Boolean(selected)} title={revenue ? 'Revenue Collection Details' : 'Management of IPAF Details'} subtitle={selected?.protected_area_name || ''} onClose={close} canEdit={canUpdate} canDelete={canDelete} onEdit={() => openEdit(selected)} onDelete={() => setDeleting(selected)} summary={selected && <CrudSummaryGrid items={revenue ? [{ label: 'Reporting Period', value: `${months[selected.reporting_month - 1]} ${selected.reporting_year}` }, { label: 'Deadline', value: formatReportDate(selected.deadline_submission) }, { label: 'Timeliness', render: () => <Badge value={selected.timeliness} /> }, { label: 'Submission Status', render: () => <Badge value={selected.submission_status} /> }] : [{ label: 'Reporting Period', value: show(selected.reporting_period || selected.semester || selected.quarter) }, { label: 'Deadline', value: formatReportDate(selected.deadline_submission) }, { label: 'Timeliness', render: () => <Badge value={selected.timeliness} /> }, { label: 'Submission Status', render: () => <Badge value={selected.submission_status} /> }]} />} attachments={selected && (selected.mov ? <FilePreviewPanel file={selected.mov} title="Report Attachment / MOV" heightClass="h-[420px]" /> : <CrudSection title="Attachment / MOV"><p className="text-xs font-semibold text-amber-700 dark:text-amber-300">Not Yet Submitted / Missing</p>{canUpdate && <button type="button" onClick={() => openEdit(selected)} className="mt-3 rounded-xl bg-green-700 px-4 py-2 text-xs font-bold text-white hover:bg-green-800">Attach MOV</button>}</CrudSection>)}><Details record={selected} revenue={revenue} /></CrudDetailsModal>
        <CrudFormModal open={modal === 'create' || modal === 'edit'} mode={modal === 'edit' ? 'edit' : 'create'} title={`${modal === 'edit' ? 'Edit' : 'Add'} ${revenue ? 'Revenue Collection' : 'Management of IPAF'}`} subtitle={revenue ? 'Monthly IPAF revenue collection and submission details.' : '7-working-day Standard-B report submission.'} onClose={close} onSubmit={submit} processing={form.processing} errors={form.errors} saveLabel={modal === 'edit' ? 'Update Record' : 'Save Record'} preview={<FilePreviewPanel file={preview} title="Live Document Preview" />}><FormFields revenue={revenue} form={form} protectedAreas={protectedAreas} selected={selected} preview={preview} setPreview={setPreview} selectMov={selectMov} /></CrudFormModal>
        <ConfirmDialog open={Boolean(deleting)} variant="danger" title="Delete IPAF Record?" message="This action cannot be undone." confirmLabel="Delete Record" onCancel={() => setDeleting(null)} onConfirm={() => router.delete(route(`${prefix}.destroy`, deleting.id), { onSuccess: () => {setDeleting(null);close();} })} />
    </div>;
}

function FormFields({ revenue, form, protectedAreas, selected, preview, setPreview, selectMov }) {
  const change = (name) => (event) => form.setData(name, event.target.value);
  const error = (name) => form.errors[name] && <span className="mt-1 block text-xs text-red-500">{form.errors[name]}</span>;
  const split = liveSplit(form.data.total_collected);

  return <>
    <CrudSection title="Report Information"><div className="grid gap-4 sm:grid-cols-2">
      <div className={label}><FloatingInput id="index-target-office" label="Target Office" required value={form.data.target_office} onChange={change('target_office')} />{error('target_office')}</div>
      <div className={label}><FloatingSelect id="index-protected-area" label="Name of PA" required value={form.data.protected_area_id} onChange={change('protected_area_id')}><option value="">Select Protected Area</option>{protectedAreas.map((pa) => <option key={pa.id} value={pa.id}>{pa.name}</option>)}</FloatingSelect>{error('protected_area_id')}</div>
      {revenue && <><div className={label}><FloatingSelect id="index-reporting-month" label="Reporting Month" required value={form.data.reporting_month} onChange={change('reporting_month')}>{months.map((month, index) => <option key={month} value={index + 1}>{month}</option>)}</FloatingSelect>{error('reporting_month')}</div><div className={label}><FloatingInput id="index-reporting-year" label="Reporting Year" required type="number" value={form.data.reporting_year} onChange={change('reporting_year')} size="sm" />{error('reporting_year')}</div></>}
      <div className={label}><FloatingSelect id="index-type-of-document" label="Type of Document" required value={form.data.document_type} onChange={change('document_type')}><option value="">Select Type of Document</option><option>Final Report</option><option>Progress Report</option></FloatingSelect>{error('document_type')}</div>
      {!revenue && <div className={label}><FloatingInput id="index-date-conducted" label="Date Conducted" value={form.data.date_conducted} onChange={change('date_conducted')} />{error('date_conducted')}</div>}
    </div></CrudSection>
    {revenue && <CrudSection title="Revenue Collection"><div className={label}><FloatingInput id="index-total-collected" label="Total Collected" required type="number" min="0" step="0.01" value={form.data.total_collected} onChange={change('total_collected')} />{error('total_collected')}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Read label="IPAF RIA (75%)" value={money(split.ria)} /><Read label="SAGF (25%)" value={money(split.sagf)} /></div></CrudSection>}
    <CrudSection title="Compliance Basis"><div className="grid gap-4 sm:grid-cols-2">{revenue ? <div className={label}><FloatingInput id="ipaf-deadline-submission" label="Deadline for Submission to PENRO" required type="date" value={form.data.deadline_submission || ''} onChange={change('deadline_submission')} />{error('deadline_submission')}</div> : <div className={label}><FloatingInput id="index-date-accomplished" label="Date Accomplished" type="date" value={form.data.date_accomplished || ''} onChange={change('date_accomplished')} />{error('date_accomplished')}</div>}</div></CrudSection>
    <CrudSection title="Attachment / MOV & Remarks"><div className="space-y-5"><FileAttachmentPanel id={`ipaf-${revenue ? 'revenue' : 'management'}-mov`} label="Report Attachment / MOV" required={!selected?.id} accept=".pdf,.jpg,.jpeg,.png,.doc,.docx" acceptedTypesHint="PDF, JPG, PNG, DOC, or DOCX" maxSizeHint="Maximum 10 MB" existingFiles={selected?.mov ? [selected.mov] : []} selectedFiles={form.data.mov ? [form.data.mov] : []} activeFile={preview} onSelectFile={setPreview} onChange={selectMov} error={form.errors.mov} disabled={form.processing} canManage /><div className={label}><FloatingTextarea id="index-remarks" label="Remarks" rows="4" value={form.data.remarks} onChange={change('remarks')} />{error('remarks')}</div></div></CrudSection>
  </>;
}
function Read({ label: heading, value }) {return <div className="rounded-xl border border-gray-200 bg-gray-50 p-3 dark:border-gray-700 dark:bg-gray-900"><p className="text-[11px] font-bold uppercase text-gray-500">{heading}</p><p className="mt-1 text-sm font-bold dark:text-white">{value}</p></div>;}
function Details({ record, revenue }) {if (!record) return null;return <div className="space-y-5"><CrudSection title="General Information"><div className="grid gap-4 sm:grid-cols-2"><Detail label="Target Office">{show(record.target_office)}</Detail><Detail label="Protected Area">{show(record.protected_area_name)}</Detail><Detail label="Activity">{show(record.activity_name)}</Detail><Detail label="Type of Document">{show(record.document_type)}</Detail>{!revenue && <Detail label="Date Conducted">{show(record.date_conducted)}</Detail>}</div></CrudSection>{revenue && <CrudSection title="Financial Details"><div className="grid gap-4 sm:grid-cols-3"><Detail label="Total Collected">{money(record.total_collected)}</Detail><Detail label="IPAF RIA 75%">{money(record.ipaf_ria)}</Detail><Detail label="SAGF 25%">{money(record.sagf)}</Detail></div></CrudSection>}<CrudSection title="Submission Timeline"><div className="grid gap-4 sm:grid-cols-2">{!revenue && <Detail label="Date Accomplished">{formatReportDate(record.date_accomplished)}</Detail>}<Detail label="CENRO Released">{!revenue && record.cenro_release_applicable === false ? <Badge value="Not Applicable — PENRO-managed Protected Area" /> : formatReportDate(record.date_report_released_cenro)}</Detail><Detail label="PENRO Received">{formatReportDate(record.date_received_penro)}</Detail><Detail label="Days Complied">{show(record.number_days_complied)}</Detail><Detail label="Endorsed Regional">{!revenue && record.cenro_release_applicable === false ? (!record.date_received_penro ? <Badge value="Not Yet Available" /> : !record.date_endorsed_regional ? <Badge value="For Endorsement" /> : formatReportDate(record.date_endorsed_regional)) : formatReportDate(record.date_endorsed_regional)}</Detail>{!revenue && <Detail label="PENRO Delay">{show(record.total_days_delayed_penro)}</Detail>}</div></CrudSection><CrudSection title="Remarks"><p>{record.remarks || 'None.'}</p></CrudSection></div>;}
function liveSplit(value) {const cents = Math.round(Number(value || 0) * 100);const ria = Math.round(cents * .75);return { ria: ria / 100, sagf: (cents - ria) / 100 };}
